#!/usr/bin/env npx tsx
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFatfWorkbook } from "./lib/fatfAssessmentParser.js";
import type {
  FatfAssessmentMethodology,
  FatfAssessmentRecord,
} from "../../src/data/fatfAssessmentData.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(ROOT, "src", "data", "fatfAssessmentData.ts");
const SOURCE_PAGE =
  "https://www.fatf-gafi.org/en/publications/Mutualevaluations/Assessment-ratings.html";
const URLS: Record<FatfAssessmentMethodology, string> = {
  "2013": "https://www.fatf-gafi.org/content/dam/fatf-gafi/Global-Network/consolidated-assessment-ratings-2013-methodology.xlsx.coredownload.inline.xlsx",
  "2022": "https://www.fatf-gafi.org/content/dam/fatf-gafi/Global-Network/consolidated-assessment-ratings-2022-methodology.xlsx.coredownload.inline.xlsx",
};

function arg(name: string): string | undefined {
  const inline = process.argv.find((value) => value.startsWith(`--${name}=`));
  if (inline) return inline.slice(name.length + 3);
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

async function load(methodology: FatfAssessmentMethodology): Promise<Buffer> {
  const local = arg(`file-${methodology}`);
  if (local) return readFile(local);
  const response = await fetch(URLS[methodology], {
    headers: { "User-Agent": "Mozilla/5.0 RegActions-Country-Risk/2.0" },
    signal: AbortSignal.timeout(60_000),
  });
  if (!response.ok) throw new Error(`FATF ${methodology} fetch HTTP ${response.status}`);
  const buffer = Buffer.from(await response.arrayBuffer());
  if ((response.headers.get("content-type") ?? "").includes("text/html")) {
    throw new Error(
      `FATF ${methodology} returned HTML. Download the official workbook in a browser and rerun with --file-${methodology}.`,
    );
  }
  return buffer;
}

function render(records: FatfAssessmentRecord[], hash: string, retrievedAt: string): string {
  const entries = records.map((record) => `  ${JSON.stringify(record.iso2)}: ${JSON.stringify(record)},`).join("\n");
  return `/** GENERATED by scripts/country-risk/ingest-fatf-assessments.ts from official FATF workbooks. */
export type FatfAssessmentMethodology = "2013" | "2022";
export type FatfEffectivenessRating = "HE" | "SE" | "ME" | "LE";
export type FatfTechnicalRating = "C" | "LC" | "PC" | "NC";
export interface FatfAssessmentRecord {
  iso2: string;
  country: string;
  methodology: FatfAssessmentMethodology;
  assessmentDate?: string;
  effectiveness: Partial<Record<\`IO\${number}\`, FatfEffectivenessRating>>;
  technicalCompliance: Partial<Record<\`R\${number}\`, FatfTechnicalRating>>;
}
export const FATF_ASSESSMENT_SOURCE = ${JSON.stringify(SOURCE_PAGE)};
export const FATF_ASSESSMENT_RETRIEVED_AT = ${JSON.stringify(retrievedAt)};
export const FATF_ASSESSMENT_SHA256 = ${JSON.stringify(hash)};
export const FATF_ASSESSMENT_RECORDS: Record<string, FatfAssessmentRecord> = {
${entries}
};
export function getFatfAssessment(iso2: string): FatfAssessmentRecord | undefined {
  return FATF_ASSESSMENT_RECORDS[iso2.toUpperCase()];
}
`;
}

async function main() {
  const buffers = await Promise.all([load("2013"), load("2022")]);
  const parsed2013 = parseFatfWorkbook(buffers[0], "2013");
  const parsed2022 = parseFatfWorkbook(buffers[1], "2022");
  if (parsed2013.records.length < 100) {
    throw new Error(`FATF 2013 coverage too small: ${parsed2013.records.length}`);
  }
  const merged = new Map(parsed2013.records.map((record) => [record.iso2, record]));
  for (const record of parsed2022.records) merged.set(record.iso2, record);
  const unresolved = [...new Set([...parsed2013.unresolvedCountries, ...parsed2022.unresolvedCountries])];
  if (unresolved.length) {
    throw new Error(`Unresolved FATF countries: ${unresolved.join(", ")}`);
  }

  const records = [...merged.values()].sort((a, b) => a.country.localeCompare(b.country));
  const hash = createHash("sha256").update(buffers[0]).update(buffers[1]).digest("hex");
  const retrievedAt = new Date().toISOString();
  console.log(`FATF assessments: ${records.length} countries (${parsed2022.records.length} on 2022 methodology)`);
  if (process.argv.includes("--dry-run")) return;
  await writeFile(OUT, render(records, hash, retrievedAt));
  console.log(`Wrote ${OUT}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
