#!/usr/bin/env npx tsx
import "dotenv/config";
import { createHash } from "node:crypto";
import { readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { buildPgPoolConfig, resolveConnectionString } from "../../server/db.js";
import { SANCTIONS_REGIME_CANDIDATES } from "../../src/data/sanctionsRegimeCandidates.js";
import {
  buildPromotedSanctionsSnapshot,
  type SanctionsCatalogueInventoryItem,
  type SanctionsCatalogueItemReviewRow,
  type SanctionsCatalogueReviewRow,
  type SanctionsReviewRow,
  type SanctionsSourceAssuranceReport,
} from "./lib/sanctionsPromotion.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUTPUT_PATH = join(ROOT, "src", "data", "sanctionsApprovedData.ts");
const SOURCE_REPORT_PATH = process.env.COUNTRY_RISK_SOURCE_REPORT
  ?? "/tmp/country-risk-sanctions-review.json";
const CENSUS_REPORT_PATH = process.env.COUNTRY_RISK_SANCTIONS_CENSUS_JSON
  ?? "/tmp/country-risk-sanctions-census.json";

function renderSnapshot(snapshot: ReturnType<typeof buildPromotedSanctionsSnapshot>): string {
  return `/** GENERATED by scripts/country-risk/promote-sanctions-snapshot.ts.
 * Do not hand-edit. Promotion requires complete independent review and a
 * current, stable four-source assurance report.
 */
import type {
  CountrySanctions,
  SanctionsImposer,
  SanctionsProgram,
  SanctionsTier,
} from "./sanctionsStatus.js";
import type { SanctionsRegimeRelationship } from "./sanctionsRegimeCandidates.js";
import type { SanctionsCoverageState, SanctionsLegalStatus, SanctionsMeasureType } from "./sanctionsEvidence.js";

export interface ApprovedSanctionsProgram extends SanctionsProgram {
  imposer: SanctionsImposer;
  tier: SanctionsTier;
  relationship: SanctionsRegimeRelationship;
  catalogueUrl: string;
  evidenceUrl: string;
  reviewedBy: string;
  reviewerOrganisation: string;
  reviewedAt: string;
  reviewNote: string;
  legalStatus: SanctionsLegalStatus;
  legalInstrumentId: string;
  legalInstrumentUrl: string;
  officialGuidanceUrl: string | null;
  legalEffectiveFrom: string;
  legalEffectiveTo: string | null;
  measures: SanctionsMeasureType[];
  evidenceLocator: string;
}

export interface ApprovedCountrySanctions extends CountrySanctions {
  programs: ApprovedSanctionsProgram[];
}

export interface ApprovedSanctionsSource {
  id: string;
  url: string;
  retrievedAt: string;
  rawSha256: string;
  fingerprint: string;
}

export interface ApprovedSanctionsSnapshotMetadata {
  version: string | null;
  coverageComplete: boolean;
  effectiveAt: string | null;
  generatedAt: string | null;
  sha256: string | null;
  sourceReportSha256: string | null;
  candidateCount: number;
  approvedCount: number;
  rejectedCount: number;
  countryCount: number;
  sources: ApprovedSanctionsSource[];
  coverageCellCount: number;
}

export interface ApprovedSanctionsCoverageCell {
  iso2: string;
  imposer: SanctionsImposer;
  state: SanctionsCoverageState;
  regimeCount: number;
  evidenceUrls: string[];
}

export const SANCTIONS_APPROVED_SNAPSHOT: ApprovedSanctionsSnapshotMetadata = ${JSON.stringify(snapshot.metadata, null, 2)};

export const SANCTIONS_APPROVED_STATUS: ApprovedCountrySanctions[] = ${JSON.stringify(snapshot.countries, null, 2)};

export const SANCTIONS_APPROVED_COVERAGE: ApprovedSanctionsCoverageCell[] = ${JSON.stringify(snapshot.coverage, null, 2)};

const BY_ISO2 = new Map(SANCTIONS_APPROVED_STATUS.map((record) => [record.iso2, record]));

export function getApprovedSanctions(iso2: string): ApprovedCountrySanctions | undefined {
  return BY_ISO2.get(iso2.toUpperCase());
}

export function getApprovedSanctionsCoverage(iso2: string): ApprovedSanctionsCoverageCell[] {
  const code = iso2.toUpperCase();
  return SANCTIONS_APPROVED_COVERAGE.filter((record) => record.iso2 === code);
}
`;
}

async function persistSnapshot(
  client: pg.PoolClient,
  snapshot: ReturnType<typeof buildPromotedSanctionsSnapshot>,
): Promise<void> {
  await client.query(
    `INSERT INTO country_risk_sanctions_snapshots (
       version, effective_at, generated_at, sha256, source_report_sha256,
       candidate_count, approved_count, rejected_count, coverage_cell_count,
       metadata
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)
     ON CONFLICT (version) DO NOTHING`,
    [
      snapshot.metadata.version,
      snapshot.metadata.effectiveAt,
      snapshot.metadata.generatedAt,
      snapshot.metadata.sha256,
      snapshot.metadata.sourceReportSha256,
      snapshot.metadata.candidateCount,
      snapshot.metadata.approvedCount,
      snapshot.metadata.rejectedCount,
      snapshot.metadata.coverageCellCount,
      JSON.stringify(snapshot.metadata),
    ],
  );
  for (const cell of snapshot.coverage) {
    await client.query(
      `INSERT INTO country_risk_sanctions_coverage_cells (
         snapshot_version, iso2, imposer, coverage_state, regime_count, evidence
       ) VALUES ($1,$2,$3,$4,$5,$6::jsonb)
       ON CONFLICT (snapshot_version, iso2, imposer) DO NOTHING`,
      [
        snapshot.metadata.version,
        cell.iso2,
        cell.imposer,
        cell.state,
        cell.regimeCount,
        JSON.stringify({ urls: cell.evidenceUrls }),
      ],
    );
  }
}

async function main() {
  const connectionString = resolveConnectionString();
  if (!connectionString) throw new Error("DATABASE_URL is required");
  const sourceReport = JSON.parse(await readFile(SOURCE_REPORT_PATH, "utf8")) as SanctionsSourceAssuranceReport;
  const censusRaw = await readFile(CENSUS_REPORT_PATH);
  const census = JSON.parse(censusRaw.toString("utf8")) as {
    automatedDiscoveryGapsResolved?: boolean;
    inventoryDispositions?: Array<{
      imposer: SanctionsCatalogueInventoryItem["imposer"];
      itemKey: string;
      label: string;
      url: string;
      candidateKeys: string[];
    }>;
  };
  if (!census.automatedDiscoveryGapsResolved || !census.inventoryDispositions?.length) {
    throw new Error("Sanctions census still contains unresolved automated discovery gaps");
  }
  const censusSha256 = createHash("sha256").update(censusRaw).digest("hex");
  const pool = new pg.Pool(buildPgPoolConfig(connectionString));
  try {
    const result = await pool.query<SanctionsReviewRow>(
      `SELECT iso2, imposer, regime_name, relationship, proposed_tier, final_tier,
              catalogue_url, measure_evidence_url, decision_evidence_url,
              effective_at, status, reviewed_by, reviewer_organisation,
              reviewed_at, review_note, legal_status, coverage_state,
              legal_instrument_id, legal_instrument_url, official_guidance_url,
              legal_effective_from, legal_effective_to, source_last_updated,
              evidence_locator, measures, broad_trade_prohibition,
              broad_financial_prohibition, material_non_designation_restriction,
              prepared_by, prepared_at
       FROM country_risk_sanctions_regimes
       ORDER BY iso2, imposer, regime_name`,
    );
    const catalogueResult = await pool.query<SanctionsCatalogueReviewRow>(
      `SELECT imposer, source_id, catalogue_url, source_fingerprint, census_sha256, status,
              reviewed_by, reviewer_organisation, reviewed_at, review_note
       FROM country_risk_sanctions_catalogue_reviews
       ORDER BY imposer`,
    );
    const catalogueItemResult = await pool.query<SanctionsCatalogueItemReviewRow>(
      `SELECT census_sha256, imposer, item_key, label, url, disposition, candidate_keys,
              reviewed_by, reviewed_at, review_note
       FROM country_risk_sanctions_catalogue_item_reviews
       WHERE census_sha256=$1
       ORDER BY imposer, item_key`,
      [censusSha256],
    );
    const asOf = new Date();
    const snapshot = buildPromotedSanctionsSnapshot({
      candidates: SANCTIONS_REGIME_CANDIDATES,
      rows: result.rows,
      catalogueReviews: catalogueResult.rows,
      censusInventory: census.inventoryDispositions.map((item) => ({
        imposer: item.imposer,
        item_key: item.itemKey,
        label: item.label,
        url: item.url,
        candidate_keys: item.candidateKeys,
      })),
      catalogueItemReviews: catalogueItemResult.rows,
      censusSha256,
      sourceReport,
      asOf,
    });
    if (process.argv.includes("--dry-run")) {
      console.log(JSON.stringify({ dryRun: true, output: OUTPUT_PATH, ...snapshot.metadata }, null, 2));
      return;
    }
    const temporaryOutput = `${OUTPUT_PATH}.tmp`;
    await writeFile(temporaryOutput, renderSnapshot(snapshot));
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      await persistSnapshot(client, snapshot);
      await client.query("COMMIT");
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }
    await rename(temporaryOutput, OUTPUT_PATH);
    console.log(JSON.stringify({ written: OUTPUT_PATH, ...snapshot.metadata }, null, 2));
  } finally {
    await pool.end();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
