#!/usr/bin/env npx tsx
import "dotenv/config";
import { readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { buildPgPoolConfig, resolveConnectionString } from "../../server/db.js";
import { SANCTIONS_REGIME_CANDIDATES } from "../../src/data/sanctionsRegimeCandidates.js";
import {
  buildPromotedSanctionsSnapshot,
  type SanctionsReviewRow,
  type SanctionsSourceAssuranceReport,
} from "./lib/sanctionsPromotion.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUTPUT_PATH = join(ROOT, "src", "data", "sanctionsApprovedData.ts");
const SOURCE_REPORT_PATH = process.env.COUNTRY_RISK_SOURCE_REPORT
  ?? "/tmp/country-risk-sanctions-review.json";

function renderSnapshot(snapshot: ReturnType<typeof buildPromotedSanctionsSnapshot>): string {
  return `/** GENERATED by scripts/country-risk/promote-sanctions-snapshot.ts.\n * Do not hand-edit. Promotion requires complete independent review and a\n * current, stable four-source assurance report.\n */\nimport type {\n  CountrySanctions,\n  SanctionsImposer,\n  SanctionsProgram,\n  SanctionsTier,\n} from "./sanctionsStatus.js";\nimport type { SanctionsRegimeRelationship } from "./sanctionsRegimeCandidates.js";\n\nexport interface ApprovedSanctionsProgram extends SanctionsProgram {\n  imposer: SanctionsImposer;\n  tier: SanctionsTier;\n  relationship: SanctionsRegimeRelationship;\n  catalogueUrl: string;\n  evidenceUrl: string;\n  reviewedBy: string;\n  reviewerOrganisation: string;\n  reviewedAt: string;\n  reviewNote: string;\n}\n\nexport interface ApprovedCountrySanctions extends CountrySanctions {\n  programs: ApprovedSanctionsProgram[];\n}\n\nexport interface ApprovedSanctionsSource {\n  id: string;\n  url: string;\n  retrievedAt: string;\n  rawSha256: string;\n  fingerprint: string;\n}\n\nexport interface ApprovedSanctionsSnapshotMetadata {\n  version: string | null;\n  coverageComplete: boolean;\n  effectiveAt: string | null;\n  generatedAt: string | null;\n  sha256: string | null;\n  sourceReportSha256: string | null;\n  candidateCount: number;\n  approvedCount: number;\n  rejectedCount: number;\n  countryCount: number;\n  sources: ApprovedSanctionsSource[];\n}\n\nexport const SANCTIONS_APPROVED_SNAPSHOT: ApprovedSanctionsSnapshotMetadata = ${JSON.stringify(snapshot.metadata, null, 2)};\n\nexport const SANCTIONS_APPROVED_STATUS: ApprovedCountrySanctions[] = ${JSON.stringify(snapshot.countries, null, 2)};\n\nconst BY_ISO2 = new Map(SANCTIONS_APPROVED_STATUS.map((record) => [record.iso2, record]));\n\nexport function getApprovedSanctions(iso2: string): ApprovedCountrySanctions | undefined {\n  return BY_ISO2.get(iso2.toUpperCase());\n}\n`;
}

async function main() {
  const connectionString = resolveConnectionString();
  if (!connectionString) throw new Error("DATABASE_URL is required");
  const sourceReport = JSON.parse(await readFile(SOURCE_REPORT_PATH, "utf8")) as SanctionsSourceAssuranceReport;
  const pool = new pg.Pool(buildPgPoolConfig(connectionString));
  try {
    const result = await pool.query<SanctionsReviewRow>(
      `SELECT iso2, imposer, regime_name, relationship, proposed_tier, final_tier,
              catalogue_url, measure_evidence_url, decision_evidence_url,
              effective_at, status, reviewed_by, reviewer_organisation,
              reviewed_at, review_note
       FROM country_risk_sanctions_regimes
       ORDER BY iso2, imposer, regime_name`,
    );
    const asOf = new Date();
    const snapshot = buildPromotedSanctionsSnapshot({
      candidates: SANCTIONS_REGIME_CANDIDATES,
      rows: result.rows,
      sourceReport,
      asOf,
    });
    if (process.argv.includes("--dry-run")) {
      console.log(JSON.stringify({ dryRun: true, output: OUTPUT_PATH, ...snapshot.metadata }, null, 2));
      return;
    }
    const temporaryOutput = `${OUTPUT_PATH}.tmp`;
    await writeFile(temporaryOutput, renderSnapshot(snapshot));
    await rename(temporaryOutput, OUTPUT_PATH);
    console.log(JSON.stringify({ written: OUTPUT_PATH, ...snapshot.metadata }, null, 2));
  } finally {
    await pool.end();
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
