#!/usr/bin/env npx tsx
/**
 * Generate a card-sized index of published articles.
 *
 * src/data/blogArticles.ts is 658 KB of source because every article carries its
 * full `content` string. The homepage imports it to render three preview cards,
 * so every visitor to the front page downloaded a 985 KB chunk containing the
 * body of every article on the site — measured on production, 29% of the
 * homepage's JavaScript.
 *
 * The cards need six fields. This emits exactly those, and the homepage imports
 * the index instead. blogArticles.ts is unchanged and remains the source of
 * truth for the blog itself.
 *
 * The output is committed, so it can go stale. blogArticleIndex.test.ts
 * regenerates it in memory and fails if it no longer matches, which is the same
 * guard the other generated data files use.
 *
 *   npx tsx scripts/generate-blog-index.ts            # dry run, reports drift
 *   npx tsx scripts/generate-blog-index.ts --write
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getPublishedBlogArticles } from "../src/data/blogArticles.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "data", "blogArticleIndex.ts");

export interface BlogArticleCard {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  dateISO: string;
}

export function buildBlogIndexSource(): string {
  const published = getPublishedBlogArticles();
  const cards: BlogArticleCard[] = published
    .map((article) => ({
      slug: article.slug,
      title: article.title,
      excerpt: article.excerpt,
      category: article.category,
      date: article.date,
      dateISO: article.dateISO,
    }))
    .sort((left, right) => right.dateISO.localeCompare(left.dateISO));

  return `/** GENERATED by scripts/generate-blog-index.ts. Do not edit by hand. */

/**
 * Card-sized article metadata for surfaces that list articles without reading
 * them. Importing blogArticles.ts pulls in every article body; this does not.
 */
export interface BlogArticleCard {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  dateISO: string;
}

/** Published articles, newest first. */
export const BLOG_ARTICLE_INDEX: BlogArticleCard[] = ${JSON.stringify(cards, null, 2)};

/** Total published articles, for "all N insights" style counts. */
export const BLOG_ARTICLE_COUNT = ${cards.length};
`;
}

async function main() {
  const next = buildBlogIndexSource();
  const current = await readFile(OUT, "utf8").catch(() => "");
  const stale = current !== next;

  if (!process.argv.includes("--write")) {
    console.log(stale ? "STALE: run with --write to regenerate" : "up to date");
    process.exit(stale ? 1 : 0);
  }
  await writeFile(OUT, next, "utf8");
  console.log(`Wrote ${OUT}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((error) => {
    console.error("Blog index generation failed:", error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
