#!/usr/bin/env npx tsx
/**
 * Ingest World Bank WGI → src/data/governanceData.ts snapshot.
 *
 * WGI now lives on the World Bank data360 platform. For each of the six WGI
 * dimensions we pull the percentile-rank measure (COMP_BREAKDOWN_1 = "WGI_SC",
 * 0–100) for the latest year across all countries, then average the available
 * dimensions per country. WGI is CC BY 4.0 (World Bank), attribution required.
 *
 * Run where data360api.worldbank.org is reachable:
 *   npx tsx scripts/ingest-wgi.ts            # write the snapshot
 *   npx tsx scripts/ingest-wgi.ts --dry-run  # print, don't write
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { COUNTRIES, getCountryByIso3 } from "../src/data/countries.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "data", "governanceData.ts");
const dryRun = process.argv.includes("--dry-run");

const BASE = "https://data360api.worldbank.org/data360/data";
const INDICATORS = [
  "GOV_WGI_CC", // Control of Corruption
  "GOV_WGI_GE", // Government Effectiveness
  "GOV_WGI_PV", // Political Stability
  "GOV_WGI_RL", // Rule of Law
  "GOV_WGI_RQ", // Regulatory Quality
  "GOV_WGI_VA", // Voice & Accountability
];
const YEAR = process.argv.find((a) => a.startsWith("--year="))?.split("=")[1] ?? "2023";

interface Row {
  REF_AREA: string;
  OBS_VALUE: string;
  COMP_BREAKDOWN_1: string;
}

async function fetchPercentiles(indicator: string): Promise<Map<string, number>> {
  const url =
    `${BASE}?DATABASE_ID=WB_WGI&INDICATOR=${indicator}` +
    `&COMP_BREAKDOWN_1=WGI_SC&timePeriodFrom=${YEAR}&timePeriodTo=${YEAR}&per_page=1000`;
  const map = new Map<string, number>();
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(45_000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = (await res.json()) as { value?: Row[] };
      for (const r of json.value ?? []) {
        if (r.COMP_BREAKDOWN_1 !== "WGI_SC") continue; // percentile rank only
        const v = Number(r.OBS_VALUE);
        if (!Number.isNaN(v)) map.set(r.REF_AREA, v);
      }
      return map;
    } catch (err) {
      if (attempt === 3) {
        console.error(`  ${indicator} failed: ${err instanceof Error ? err.message : err}`);
        return map;
      }
      await new Promise((r) => setTimeout(r, 3000));
    }
  }
  return map;
}

function renderFile(map: Record<string, number>): string {
  const entries = Object.entries(map)
    .sort((a, b) => b[1] - a[1])
    .map(([iso2, pct]) => `  ${iso2}: ${pct},`)
    .join("\n");
  return `/**
 * World Bank Worldwide Governance Indicators (WGI) — snapshot.
 *
 * Single mean-percentile per country (0–100, HIGHER = BETTER governance): the
 * average of the six WGI dimensions' percentile ranks (WGI_SC). Scored
 * governance pillar of the Country Risk Score. CC BY 4.0 (World Bank),
 * attribution required.
 *
 * GENERATED by scripts/ingest-wgi.ts from the World Bank data360 API (WGI ${YEAR}
 * data). Do not edit by hand — re-run to refresh.
 */

export const GOVERNANCE_SOURCE =
  "https://www.worldbank.org/en/publication/worldwide-governance-indicators";
export const GOVERNANCE_VINTAGE = "${YEAR}";
export const GOVERNANCE_LICENCE = "CC BY 4.0 — World Bank WGI";

/** iso2 -> mean WGI percentile (0–100, higher = better governance). */
export const GOVERNANCE_PERCENTILE: Record<string, number> = {
${entries}
};

export function getGovernancePercentile(iso2: string): number | undefined {
  return GOVERNANCE_PERCENTILE[iso2.toUpperCase()];
}

export function hasGovernanceData(iso2: string): boolean {
  return iso2.toUpperCase() in GOVERNANCE_PERCENTILE;
}
`;
}

async function main(): Promise<void> {
  console.log(`Fetching WGI ${YEAR} (6 dimensions) from data360…`);
  const perIndicator = new Map<string, Map<string, number>>();
  for (const ind of INDICATORS) {
    const m = await fetchPercentiles(ind);
    perIndicator.set(ind, m);
    console.log(`  ${ind}: ${m.size} countries`);
  }

  // Average the available dimensions per ISO3, then map to ISO2.
  const iso3s = new Set<string>();
  for (const m of perIndicator.values()) for (const k of m.keys()) iso3s.add(k);

  const map: Record<string, number> = {};
  for (const iso3 of iso3s) {
    const country = getCountryByIso3(iso3);
    if (!country) continue; // skip aggregates/regions not in our reference
    const vals: number[] = [];
    for (const m of perIndicator.values()) {
      const v = m.get(iso3);
      if (v !== undefined) vals.push(v);
    }
    if (vals.length === 0) continue;
    map[country.iso2] = Math.round(vals.reduce((s, v) => s + v, 0) / vals.length);
  }

  console.log(
    `Resolved mean WGI percentile for ${Object.keys(map).length}/${COUNTRIES.length} reference countries.`,
  );
  if (dryRun) {
    console.log(JSON.stringify(map, null, 2));
    return;
  }
  writeFileSync(OUT, renderFile(map));
  console.log(`Wrote ${OUT}`);
}

main();
