#!/usr/bin/env npx tsx
/**
 * Ingest World Bank WGI → src/data/governanceData.ts snapshot.
 *
 * Fetches the six WGI percentile-rank indicators for every country in the
 * reference set, averages the available dimensions, and rewrites the
 * GOVERNANCE_PERCENTILE map. WGI is CC BY 4.0 (World Bank) — derivative use OK
 * with attribution.
 *
 * Run where api.worldbank.org is reachable (local / CI, not every sandbox):
 *   npx tsx scripts/ingest-wgi.ts            # all reference countries
 *   npx tsx scripts/ingest-wgi.ts --dry-run  # print, don't write
 */

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { COUNTRIES } from "../src/data/countries.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "data", "governanceData.ts");
const dryRun = process.argv.includes("--dry-run");

const WGI_CODES = ["VA", "PV", "GE", "RQ", "RL", "CC"].map((d) => `${d}.PER.RNK`);
const API = "https://api.worldbank.org/v2";

async function fetchIndicator(iso3: string, code: string): Promise<number | null> {
  try {
    const res = await fetch(
      `${API}/country/${iso3}/indicator/${code}?format=json&mrnev=1&per_page=1`,
      { signal: AbortSignal.timeout(20_000) },
    );
    if (!res.ok) return null;
    const json = (await res.json()) as unknown;
    // Shape: [ meta, [ { value: number|null, date: string, ... } ] ]
    if (!Array.isArray(json) || json.length < 2 || !Array.isArray(json[1])) return null;
    const row = json[1][0] as { value: number | null } | undefined;
    return typeof row?.value === "number" ? row.value : null;
  } catch {
    return null;
  }
}

async function meanWgiPercentile(iso3: string): Promise<number | null> {
  const values = await Promise.all(WGI_CODES.map((c) => fetchIndicator(iso3, c)));
  const present = values.filter((v): v is number => v !== null);
  if (present.length === 0) return null;
  return Math.round(present.reduce((s, v) => s + v, 0) / present.length);
}

function renderFile(map: Record<string, number>): string {
  const entries = Object.entries(map)
    .sort((a, b) => b[1] - a[1])
    .map(([iso2, pct]) => `  ${iso2}: ${pct},`)
    .join("\n");
  return `/**
 * World Bank Worldwide Governance Indicators (WGI) — snapshot.
 *
 * Single mean-percentile per country (0–100, HIGHER = BETTER governance), the
 * average of the six WGI dimensions. Scored governance pillar of the Country
 * Risk Score. CC BY 4.0 (World Bank), attribution required.
 *
 * GENERATED by scripts/ingest-wgi.ts — do not edit by hand; re-run to refresh.
 */

export const GOVERNANCE_SOURCE =
  "https://www.worldbank.org/en/publication/worldwide-governance-indicators";
export const GOVERNANCE_VINTAGE = "${new Date().getFullYear()}";
export const GOVERNANCE_LICENCE = "CC BY 4.0 — World Bank WGI";

/** iso2 -> mean WGI percentile (0–100, higher = better governance). */
export const GOVERNANCE_PERCENTILE: Record<string, number> = {
${entries}
};

export function getGovernancePercentile(iso2: string): number | undefined {
  return GOVERNANCE_PERCENTILE[iso2.toUpperCase()];
}

export function hasGovernanceData(iso2: string): boolean {
  return iso2.toUpperCase() in GOVERNANCE_PERCENTILE;
}
`;
}

async function main(): Promise<void> {
  const map: Record<string, number> = {};
  let done = 0;
  for (const c of COUNTRIES) {
    const pct = await meanWgiPercentile(c.iso3);
    if (pct !== null) map[c.iso2] = pct;
    done += 1;
    if (done % 25 === 0) console.log(`  …${done}/${COUNTRIES.length}`);
  }
  console.log(`Fetched WGI for ${Object.keys(map).length}/${COUNTRIES.length} countries.`);
  if (dryRun) {
    console.log(JSON.stringify(map, null, 2));
    return;
  }
  writeFileSync(OUT, renderFile(map));
  console.log(`Wrote ${OUT}`);
}

main();
