#!/usr/bin/env npx tsx
/**
 * Ingest Transparency International CPI → src/data/cpiData.ts snapshot.
 *
 * CPI (Corruption Perceptions Index) is a 0–100 score, HIGHER = cleaner. It is
 * DISPLAY-ONLY here (CC BY-ND — we show it unmodified, never derive/score from
 * it; the scored corruption signal comes from World Bank WGI). We take the
 * latest year present and rank within it (standard competition ranking, ties
 * share a rank) to reproduce TI's published "#N / total".
 *
 * Data via Our World in Data's redistribution of the TI CPI (ISO3-coded, stable):
 *   npx tsx scripts/ingest-cpi.ts            # write the snapshot
 *   npx tsx scripts/ingest-cpi.ts --dry-run  # print summary, don't write
 */
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { getCountryByIso3 } from "../src/data/countries.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "data", "cpiData.ts");
const dryRun = process.argv.includes("--dry-run");

const CSV_URL =
  "https://ourworldindata.org/grapher/TI-corruption-perception-index.csv?csvType=full";

/** Split one CSV line, respecting double-quoted fields (which may contain commas). */
function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else inQuotes = !inQuotes;
    } else if (ch === "," && !inQuotes) {
      out.push(cur);
      cur = "";
    } else cur += ch;
  }
  out.push(cur);
  return out;
}

async function main() {
  const res = await fetch(CSV_URL, { signal: AbortSignal.timeout(60_000) });
  if (!res.ok) throw new Error(`CPI fetch HTTP ${res.status}`);
  const text = await res.text();
  const lines = text.trim().split("\n");
  const header = parseCsvLine(lines[0]);
  const codeIdx = header.indexOf("Code");
  const yearIdx = header.indexOf("Year");
  const scoreIdx = header.findIndex((h) => h.toLowerCase().includes("corruption"));
  if (codeIdx < 0 || yearIdx < 0 || scoreIdx < 0) {
    throw new Error(`Unexpected CPI columns: ${header.join(" | ")}`);
  }

  // Parse rows → keyed by ISO3, keep the latest year per code.
  interface Rec {
    iso3: string;
    year: number;
    score: number;
  }
  const rows: Rec[] = [];
  let latestYear = 0;
  for (let i = 1; i < lines.length; i++) {
    const cols = parseCsvLine(lines[i]);
    const iso3 = cols[codeIdx]?.trim();
    const year = Number(cols[yearIdx]);
    const score = Number(cols[scoreIdx]);
    if (!iso3 || iso3.length !== 3 || Number.isNaN(year) || Number.isNaN(score)) continue;
    rows.push({ iso3, year, score });
    if (year > latestYear) latestYear = year;
  }

  // Rank within the single latest year (matches TI's annual table).
  const current = rows.filter((r) => r.year === latestYear);
  // Sort by score desc for ranking.
  const sorted = [...current].sort((a, b) => b.score - a.score);
  const total = sorted.length;

  // Map ISO3 → our iso2, compute standard-competition rank (ties share a rank).
  interface Entry {
    iso2: string;
    name: string;
    score: number;
    rank: number;
  }
  const entries: Entry[] = [];
  for (const r of sorted) {
    const country = getCountryByIso3(r.iso3);
    if (!country) continue; // Kosovo pseudo-codes / regions OWID includes but we don't map
    const rank = 1 + current.filter((o) => o.score > r.score).length;
    entries.push({ iso2: country.iso2, name: country.name, score: r.score, rank });
  }
  // Stable order for the generated file: by rank asc, then name.
  entries.sort((a, b) => a.rank - b.rank || a.name.localeCompare(b.name));

  console.log(
    `CPI ${latestYear}: ${current.length} scored countries, ${entries.length} mapped to our ISO set (total ranked = ${total}).`,
  );
  console.log(
    "  sample:",
    entries
      .filter((e) => ["DK", "NG", "IR", "SO", "GB", "US"].includes(e.iso2))
      .map((e) => `${e.iso2} ${e.score}/#${e.rank}`)
      .join(" · "),
  );

  if (dryRun) return;

  const body = entries
    .map((e) => `  ${e.iso2}: { score: ${e.score}, rank: ${e.rank} }, // ${e.name}`)
    .join("\n");

  const file = `/**
 * Transparency International — Corruption Perceptions Index (CPI) snapshot.
 *
 * Score 0–100 (HIGHER = cleaner / less corrupt) + rank (1 = cleanest) within the
 * ${latestYear} table (${total} countries ranked; standard-competition ranking).
 *
 * DISPLAY-ONLY. CPI is licensed CC BY-ND: we show it unmodified and NEVER feed it
 * into the RegActions Country Risk Score (the scored corruption signal comes from
 * the World Bank WGI Control-of-Corruption dimension). Attribution required.
 *
 * GENERATED by scripts/ingest-cpi.ts. Do not edit by hand — re-run to refresh.
 */

export const CPI_YEAR = "${latestYear}";
export const CPI_TOTAL = ${total};
export const CPI_SOURCE = "https://www.transparency.org/en/cpi/${latestYear}";
export const CPI_LICENCE = "CC BY-ND 4.0 — Transparency International";

export interface CpiEntry {
  /** 0–100, higher = cleaner. */
  score: number;
  /** 1 = cleanest; out of CPI_TOTAL. */
  rank: number;
}

/** iso2 -> CPI score + rank (${latestYear}). Display only, never scored. */
export const CPI_RANK: Record<string, CpiEntry> = {
${body}
};

export function getCpi(iso2: string): CpiEntry | undefined {
  return CPI_RANK[iso2];
}

export function hasCpi(iso2: string): boolean {
  return iso2 in CPI_RANK;
}
`;

  writeFileSync(OUT, file);
  console.log(`Wrote ${OUT} (${entries.length} countries, CPI ${latestYear}).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
