#!/usr/bin/env npx tsx
/**
 * Ingest World Bank WGI → src/data/governanceData.ts snapshot.
 *
 * WGI lives on the World Bank data360 platform. For each of the six WGI
 * dimensions we pull the percentile-rank measure (COMP_BREAKDOWN_1 = "WGI_SC",
 * 0–100, HIGHER = BETTER) for the latest year across all countries. We store
 * BOTH the per-dimension percentiles (for the Basel-style domain breakdown:
 * corruption / rule of law / political stability) AND their mean. WGI is
 * CC BY 4.0 (World Bank), attribution required.
 *
 * Run where data360api.worldbank.org is reachable:
 *   npx tsx scripts/ingest-wgi.ts            # write the snapshot
 *   npx tsx scripts/ingest-wgi.ts --dry-run  # print, don't write
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { COUNTRIES, getCountryByIso3 } from "../src/data/countries.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "src", "data", "governanceData.ts");
const dryRun = process.argv.includes("--dry-run");

const BASE = "https://data360api.worldbank.org/data360/data";
const INDICATORS: Array<{ code: string; key: string }> = [
  { code: "GOV_WGI_CC", key: "cc" }, // Control of Corruption
  { code: "GOV_WGI_RL", key: "rl" }, // Rule of Law
  { code: "GOV_WGI_RQ", key: "rq" }, // Regulatory Quality
  { code: "GOV_WGI_GE", key: "ge" }, // Government Effectiveness
  { code: "GOV_WGI_PV", key: "pv" }, // Political Stability & Absence of Violence
  { code: "GOV_WGI_VA", key: "va" }, // Voice & Accountability
];
const DIM_KEYS = INDICATORS.map((i) => i.key);
const REQUESTED_YEAR = process.argv.find((a) => a.startsWith("--year="))?.split("=")[1];

interface Row {
  REF_AREA: string;
  OBS_VALUE: string;
  COMP_BREAKDOWN_1: string;
}

async function fetchPercentiles(indicator: string, year: string): Promise<{ values: Map<string, number>; rawSha256: string | null }> {
  const url =
    `${BASE}?DATABASE_ID=WB_WGI&INDICATOR=${indicator}` +
    `&COMP_BREAKDOWN_1=WGI_SC&timePeriodFrom=${year}&timePeriodTo=${year}&per_page=1000`;
  const map = new Map<string, number>();
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(45_000) });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = await res.text();
      const json = JSON.parse(body) as { value?: Row[] };
      if (!Array.isArray(json.value)) throw new Error("World Bank response has no value array");
      for (const r of json.value ?? []) {
        if (r.COMP_BREAKDOWN_1 !== "WGI_SC") continue; // percentile rank only
        const v = Number(r.OBS_VALUE);
        if (!Number.isNaN(v)) map.set(r.REF_AREA, v);
      }
      return { values: map, rawSha256: createHash("sha256").update(body).digest("hex") };
    } catch (err) {
      if (attempt === 3) {
        console.error(`  ${indicator} failed: ${err instanceof Error ? err.message : err}`);
        return { values: map, rawSha256: null };
      }
      await new Promise((r) => setTimeout(r, 3000));
    }
  }
  return { values: map, rawSha256: null };
}

type Dims = Record<string, number>;

function renderFile(dims: Record<string, Dims>, mean: Record<string, number>, rawSha256: string, year: string): string {
  const dimEntries = Object.entries(dims)
    .sort((a, b) => (mean[b[0]] ?? 0) - (mean[a[0]] ?? 0))
    .map(([iso2, d]) => {
      const parts = DIM_KEYS.filter((k) => d[k] !== undefined)
        .map((k) => `${k}: ${d[k]}`)
        .join(", ");
      return `  ${iso2}: { ${parts} },`;
    })
    .join("\n");
  const meanEntries = Object.entries(mean)
    .sort((a, b) => b[1] - a[1])
    .map(([iso2, pct]) => `  ${iso2}: ${pct},`)
    .join("\n");
  return `/**
 * World Bank Worldwide Governance Indicators (WGI) — snapshot.
 *
 * Per-dimension percentile ranks (0–100, HIGHER = BETTER governance) for the six
 * WGI dimensions, plus their mean. These drive the Basel-style scored domains of
 * the Country Risk Score (corruption, rule of law / institutions, political
 * stability). CC BY 4.0 (World Bank), attribution required.
 *
 * GENERATED by scripts/ingest-wgi.ts from the World Bank data360 API (WGI ${year}
 * data). Do not edit by hand — re-run to refresh.
 */

export const GOVERNANCE_SOURCE =
  "https://www.worldbank.org/en/publication/worldwide-governance-indicators";
export const GOVERNANCE_VINTAGE = "${year}";
export const GOVERNANCE_RETRIEVED_AT = "${new Date().toISOString()}";
export const GOVERNANCE_SHA256 = "${rawSha256}";
export const GOVERNANCE_LICENCE = "CC BY 4.0 — World Bank WGI";

/** The six WGI dimensions (percentile rank 0–100, higher = better). */
export interface WgiDimensions {
  /** Control of Corruption */
  cc: number;
  /** Rule of Law */
  rl: number;
  /** Regulatory Quality */
  rq: number;
  /** Government Effectiveness */
  ge: number;
  /** Political Stability & Absence of Violence */
  pv: number;
  /** Voice & Accountability */
  va: number;
}

/** iso2 -> per-dimension WGI percentiles (dimensions missing data are omitted). */
export const GOVERNANCE_DIMENSIONS: Record<string, Partial<WgiDimensions>> = {
${dimEntries}
};

/** iso2 -> mean WGI percentile (0–100, higher = better governance). */
export const GOVERNANCE_PERCENTILE: Record<string, number> = {
${meanEntries}
};

export function getGovernancePercentile(iso2: string): number | undefined {
  return GOVERNANCE_PERCENTILE[iso2.toUpperCase()];
}

export function getGovernanceDimensions(
  iso2: string,
): Partial<WgiDimensions> | undefined {
  return GOVERNANCE_DIMENSIONS[iso2.toUpperCase()];
}

export function hasGovernanceData(iso2: string): boolean {
  return iso2.toUpperCase() in GOVERNANCE_PERCENTILE;
}
`;
}

async function main(): Promise<void> {
  const first = INDICATORS[0];
  const candidates = REQUESTED_YEAR
    ? [REQUESTED_YEAR]
    : Array.from(
        { length: Math.max(1, new Date().getUTCFullYear() - 2024) },
        (_, index) => String(new Date().getUTCFullYear() - 1 - index),
      );
  let year: string | undefined;
  let firstResult: Awaited<ReturnType<typeof fetchPercentiles>> | undefined;
  for (const candidate of candidates) {
    const result = await fetchPercentiles(first.code, candidate);
    if (result.values.size >= 175 && result.rawSha256) {
      year = candidate;
      firstResult = result;
      break;
    }
    console.log(`  WGI ${candidate} is not a complete release; checking the prior year.`);
  }
  if (!year || !firstResult) throw new Error("No complete WGI release found from 2024 onward");
  console.log(`Fetching latest complete WGI release ${year} (6 dimensions) from data360…`);
  const perIndicator = new Map<string, Map<string, number>>();
  const rawHashes: Array<[string, string]> = [];
  for (const ind of INDICATORS) {
    const result = ind.code === first.code ? firstResult : await fetchPercentiles(ind.code, year);
    if (result.values.size < 175 || !result.rawSha256) {
      throw new Error(`${ind.code}: coverage too small or raw response unavailable (${result.values.size}); refusing to publish`);
    }
    perIndicator.set(ind.key, result.values);
    rawHashes.push([ind.code, result.rawSha256]);
    console.log(`  ${ind.code} (${ind.key}): ${result.values.size} countries`);
  }

  // Collect every ISO3 seen, map to ISO2, store per-dimension + mean.
  const iso3s = new Set<string>();
  for (const m of perIndicator.values()) for (const k of m.keys()) iso3s.add(k);

  const dims: Record<string, Dims> = {};
  const mean: Record<string, number> = {};
  for (const iso3 of iso3s) {
    const country = getCountryByIso3(iso3);
    if (!country) continue; // skip aggregates/regions not in our reference
    const d: Dims = {};
    const vals: number[] = [];
    for (const key of DIM_KEYS) {
      const v = perIndicator.get(key)?.get(iso3);
      if (v !== undefined) {
        d[key] = Math.round(v);
        vals.push(v);
      }
    }
    if (vals.length === 0) continue;
    dims[country.iso2] = d;
    mean[country.iso2] = Math.round(vals.reduce((s, v) => s + v, 0) / vals.length);
  }

  console.log(
    `Resolved WGI for ${Object.keys(mean).length}/${COUNTRIES.length} reference countries (per-dimension + mean).`,
  );
  if (Object.keys(mean).length < 175) {
    throw new Error(`WGI coverage too small: ${Object.keys(mean).length}; refusing to publish`);
  }
  if (dryRun) {
    console.log(JSON.stringify({ sample: Object.entries(dims).slice(0, 3), mean: Object.entries(mean).slice(0, 3), rawHashes }, null, 2));
    return;
  }
  const compositeRawSha256 = createHash("sha256").update(JSON.stringify(rawHashes)).digest("hex");
  writeFileSync(OUT, renderFile(dims, mean, compositeRawSha256, year));
  console.log(`Wrote ${OUT}`);
}

main();
