/** GENERATED by scripts/generate-blog-index.ts. Do not edit by hand. */

/**
 * Card-sized article metadata for surfaces that list articles without reading
 * them. Importing blogArticles.ts pulls in every article body; this does not.
 */
export interface BlogArticleCard {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  dateISO: string;
}

/** Published articles, newest first. */
export const BLOG_ARTICLE_INDEX: BlogArticleCard[] = [
  {
    "slug": "bafin-vs-fca-uk-german-firms",
    "title": "BaFin vs FCA: What UK Firms with German Subsidiaries Need to Know",
    "excerpt": "The FCA and BaFin enforce financial regulation in almost opposite ways. The FCA runs a low-volume, high-value, conduct-and-AML model with personal accountability built in. BaFin runs a high-volume, lower-value, disclosure-and-market-abuse model that is largely administrative. A UK firm that is FCA-ready is not automatically BaFin-ready — and for a German subsidiary, the risk profile inverts.",
    "category": "Regional Benchmark",
    "date": "August 2026",
    "dateISO": "2026-08-25"
  },
  {
    "slug": "crypto-firms-global-enforcement-mica-fca-mas",
    "title": "Crypto Firms Under MiCA, FCA and MAS: What Enforcement Looks Like Now",
    "excerpt": "If you read the headlines, crypto enforcement looks like nine-figure fines. Look at the three frameworks built specifically for crypto — the EU's MiCA, the FCA's registration regime, and MAS's licensing regime — and the picture is completely different. None of them is primarily a fining machine. All three are gatekeeping machines. For a crypto firm, the enforcement risk that should keep you up at night is not a penalty — it's losing, or never getting, permission to operate.",
    "category": "Sector Analysis",
    "date": "August 2026",
    "dateISO": "2026-08-18"
  },
  {
    "slug": "enforcement-spotlight-2026-w34",
    "title": "Enforcement Spotlight: Individual Accountability and Fraud Prevention",
    "excerpt": "Recent regulatory actions highlight a persistent focus on individual accountability, fraud in opaque markets, and procedural enforcement across multiple jurisdictions.",
    "category": "Enforcement Roundup",
    "date": "17 August 2026",
    "dateISO": "2026-08-17"
  },
  {
    "slug": "aml-kyc-enforcement-trends",
    "title": "Global AML Enforcement: Key Trends and Regulatory Expectations",
    "excerpt": "Analysis of 30 recent enforcement actions reveals a global regulatory focus on Anti-Money Laundering (AML) programme failures, with significant penalties for inadequate transaction monitoring and customer due diligence.",
    "category": "Enforcement Analysis",
    "date": "12 August 2026",
    "dateISO": "2026-08-12"
  },
  {
    "slug": "sanctions-enforcement-ofsi-ofac-eu",
    "title": "OFSI, OFAC and EU Sanctions: A Side-by-Side Enforcement Map",
    "excerpt": "Three regulators, three operating models. OFAC has the deepest enforcement history; OFSI has rebuilt its toolkit dramatically since 2022; the EU's enforcement architecture remains the most fragmented of the three. For any firm with cross-border activity, knowing how the three differ in scale, mechanics, and recent direction is no longer optional.",
    "category": "Thematic Analysis",
    "date": "August 2026",
    "dateISO": "2026-08-11"
  },
  {
    "slug": "h1-2026-enforcement-halftime",
    "title": "H1 2026 FCA Enforcement Halftime: 10 Things We Learned",
    "excerpt": "The FCA issued 9 monetary fines worth £16,842,723 in H1 2026 — up 41% in value over H1 2025 — but one action accounts for 77% of that total. Our halftime review extracts ten data-grounded lessons on where enforcement is concentrated, where the supervisory pipeline is building, and what H2 2026 is likely to bring.",
    "category": "Trends Analysis",
    "date": "August 2026",
    "dateISO": "2026-08-11"
  },
  {
    "slug": "enforcement-weekly-2026-w33",
    "title": "Global Enforcement: AML, Reporting, and Conduct Penalties (27 July-10 August)",
    "excerpt": "This analysis covers 12 global enforcement actions from 27 July to 10 August 2026, including a USD 20 million AML fine for UBS, a German financial reporting penalty, and diverse sanctions from SEBI, BaFin, and CIRO.",
    "category": "Enforcement Roundup",
    "date": "10 August 2026",
    "dateISO": "2026-08-10"
  },
  {
    "slug": "board-guide-aml-controls",
    "title": "Board Guide: Building Effective AML Controls",
    "excerpt": "Recent enforcement actions reveal systemic Anti-Money Laundering (AML) control failures. Boards must move beyond policy to ensure risk-based monitoring, independent testing.",
    "category": "Board Governance",
    "date": "7 August 2026",
    "dateISO": "2026-08-07"
  },
  {
    "slug": "regulatory-roundup-august-2026",
    "title": "July 2026 Enforcement Actions: A Regulatory Analysis",
    "excerpt": "Global regulators issued 16 public enforcement actions in July 2026. This analysis examines key cases from FINRA, BaFin, and SEBI, highlighting critical compliance and operational failures across jurisdictions.",
    "category": "Enforcement Roundup",
    "date": "3 August 2026",
    "dateISO": "2026-08-03"
  },
  {
    "slug": "fca-fines-july-2025",
    "title": "FCA Final Notices: July 2025 Enforcement Actions Analysed",
    "excerpt": "This report reviews nine FCA final notices from July 2025, covering governance, AML, reporting, and controls. Only source-verified monetary amounts are included, ensuring an evidence-led analysis of enforcement outcomes.",
    "category": "FCA Fines 2025",
    "date": "24 July 2026",
    "dateISO": "2026-07-24"
  },
  {
    "slug": "state-of-global-aml-enforcement-h1-2026",
    "title": "State of Global AML Enforcement: H1 2026",
    "excerpt": "A data study built from RegActions' live enforcement and country-risk APIs: the H1 2026 regulator league table, breach trends, FCA fines up 41% year on year, and the June FATF plenary. Free to reuse under CC BY-NC 4.0.",
    "category": "Data Studies",
    "date": "July 2026",
    "dateISO": "2026-07-17"
  },
  {
    "slug": "wealth-managers-consumer-duty-enforcement",
    "title": "Wealth Managers: Why You're at the Front of the Consumer Duty Queue",
    "excerpt": "Wealth managers carry four pre-existing risk concentrations that map directly onto the Consumer Duty's four outcomes — fees, complexity, ageing client demographics, and vertical integration. That alignment makes the sector the highest-probability source of the first wave of Consumer Duty enforcement. Here's why, what the existing enforcement record shows, and what wealth-firm boards should be doing now.",
    "category": "Sector Analysis",
    "date": "July 2026",
    "dateISO": "2026-07-05"
  },
  {
    "slug": "consumer-duty-three-years-enforcement",
    "title": "Consumer Duty Enforcement: Three Years In, Where the FCA May Act Next",
    "excerpt": "Consumer Duty enforcement guide covering customer outcomes, fair value, advice, wealth management, board MI, vulnerability, remediation and FCA evidence expectations.",
    "category": "Thematic Analysis",
    "date": "July 2026",
    "dateISO": "2026-07-03"
  },
  {
    "slug": "fca-fines-may-2026",
    "title": "FCA Fines May 2026: Individual Accountability and Pensions Advice",
    "excerpt": "May 2026 FCA fines guide covering Frank Breuer, pension transfer advice, individual accountability, permission cancellations, owner-manager risk and board evidence.",
    "category": "FCA Fines 2026",
    "date": "May 2026",
    "dateISO": "2026-07-01"
  },
  {
    "slug": "fca-vs-sec-enforcement-differences",
    "title": "FCA vs SEC Enforcement: 5 Differences That Actually Matter",
    "excerpt": "Compliance teams that operate on both sides of the Atlantic often benchmark FCA actions against SEC actions and reach the wrong conclusions. The two regulators differ on five structural points — scale, what counts as a 'fine', whistleblower incentives, individual accountability, and how political cycles bend the curve. Here's what each looks like, with the data.",
    "category": "Thematic Analysis",
    "date": "June 2026",
    "dateISO": "2026-06-23"
  },
  {
    "slug": "payments-firms-fca-aml-enforcement",
    "title": "FCA Payments Enforcement: Why It's Permissions, Not Fines",
    "excerpt": "Payments firms read AML-fine headlines and prepare for a Final Notice that never comes. The FCA's enforcement tool against this sector is overwhelmingly permissions cancellation — and the volume has grown nearly 10x in five years. Here's what the data shows, why the regulator favours this route, and what payments-firm compliance teams should be doing about it.",
    "category": "Sector Analysis",
    "date": "June 2026",
    "dateISO": "2026-06-16"
  },
  {
    "slug": "latin-america-enforcement-cvm-cnbv-cmf",
    "title": "CVM, CNBV and CMF: Latin America Enforcement Guide",
    "excerpt": "Brazil, Mexico and Chile enforcement guide covering CVM, CNBV and CMF supervisory priorities, market conduct risk, financial crime controls and board reporting.",
    "category": "Regional Benchmark",
    "date": "10 June 2026",
    "dateISO": "2026-06-10"
  },
  {
    "slug": "dora-enforcement-18-months",
    "title": "DORA at 18 Months: Why Enforcement Hasn't Started — and What's Coming",
    "excerpt": "Eighteen months after the Digital Operational Resilience Act went into application, public enforcement actions remain effectively zero. The reason isn't regulatory inertia — it's that the supervisory architecture is still being built. Here's what's happened, why fines have not yet appeared, and what compliance teams should be doing before they do.",
    "category": "Thematic Analysis",
    "date": "June 2026",
    "dateISO": "2026-06-09"
  },
  {
    "slug": "middle-east-enforcement-dfsa-fsra-cbuae",
    "title": "DFSA, FSRA, CBUAE and Saudi CMA Enforcement Guide",
    "excerpt": "Middle East financial enforcement guide covering DIFC DFSA, ADGM FSRA, CBUAE and Saudi CMA supervisory themes for AML, governance, markets and conduct.",
    "category": "Regional Benchmark",
    "date": "8 June 2026",
    "dateISO": "2026-06-08"
  },
  {
    "slug": "systems-controls-enforcement-global",
    "title": "Systems and Controls Enforcement: Global Regulator Guide",
    "excerpt": "Global systems and controls enforcement guide covering operational resilience, technology failure, management information, risk ownership and board evidence across major regulators.",
    "category": "Thematic Analysis",
    "date": "5 June 2026",
    "dateISO": "2026-06-05"
  },
  {
    "slug": "fincen-bsa-enforcement-guide",
    "title": "FinCEN Enforcement Actions: BSA/AML Penalties Guide",
    "excerpt": "FinCEN enforcement guide covering BSA/AML civil money penalties, SAR and CTR failures, MSB registration, beneficial ownership, correspondent banking and board reporting.",
    "category": "Regulatory Guide",
    "date": "3 June 2026",
    "dateISO": "2026-06-03"
  },
  {
    "slug": "fca-fines-april-2026",
    "title": "FCA Enforcement April 2026: No Fines, 11 Supervisory Actions",
    "excerpt": "For the first time in five years the FCA closed an April with zero financial penalties — but issued its busiest run of supervisory actions in that span, with motor finance suitability and pension transfers dominating the docket.",
    "category": "FCA Fines 2026",
    "date": "April 2026",
    "dateISO": "2026-06-01"
  },
  {
    "slug": "board-guide-governance-accountability-enforcement",
    "title": "Board Guide: Senior Manager Accountability Across Regulators",
    "excerpt": "Board guide to senior manager accountability across FCA, CBI, ASIC, MAS, HKMA, FINMA, OCC and SEC expectations, with practical governance evidence and committee questions.",
    "category": "Board Guide",
    "date": "1 June 2026",
    "dateISO": "2026-06-01"
  },
  {
    "slug": "switzerland-offshore-enforcement-finma-jfsc-gfsc",
    "title": "FINMA, JFSC and GFSC Offshore Enforcement Guide",
    "excerpt": "Offshore and wealth centre enforcement guide covering FINMA, Jersey JFSC, Guernsey GFSC and DFSA themes for AML, governance, funds and private wealth controls.",
    "category": "Regional Benchmark",
    "date": "29 May 2026",
    "dateISO": "2026-05-29"
  },
  {
    "slug": "market-abuse-enforcement-global-comparison",
    "title": "Market Abuse Enforcement: Global Regulator Comparison",
    "excerpt": "Global market abuse enforcement guide covering insider dealing, unlawful disclosure, market manipulation, surveillance, information barriers and cross-border regulator coordination.",
    "category": "Thematic Analysis",
    "date": "27 May 2026",
    "dateISO": "2026-05-27"
  },
  {
    "slug": "finra-ciro-sro-enforcement-comparison",
    "title": "FINRA vs CIRO: North American SRO Enforcement Compared",
    "excerpt": "Detailed FINRA and CIRO enforcement comparison for broker-dealers, investment dealers, supervision teams and compliance leaders managing US and Canadian SRO obligations.",
    "category": "Thematic Analysis",
    "date": "25 May 2026",
    "dateISO": "2026-05-25"
  },
  {
    "slug": "cbi-ireland-enforcement-guide",
    "title": "Central Bank of Ireland Enforcement Guide for UK Firms",
    "excerpt": "Practical guide to Central Bank of Ireland enforcement, the Administrative Sanctions Procedure, post-Brexit substance expectations, governance evidence, AML controls and board reporting.",
    "category": "Regulatory Guide",
    "date": "22 May 2026",
    "dateISO": "2026-05-22"
  },
  {
    "slug": "board-guide-aml-controls-global-enforcement",
    "title": "Board Guide: Global AML Controls and Enforcement Data",
    "excerpt": "Board-level AML controls guide using global enforcement data to test transaction monitoring, customer due diligence, SAR governance, remediation and senior manager evidence.",
    "category": "Board Guide",
    "date": "20 May 2026",
    "dateISO": "2026-05-20"
  },
  {
    "slug": "apac-financial-enforcement-comparison",
    "title": "APAC Financial Enforcement: ASIC, MAS, SEBI, HKMA and SFC",
    "excerpt": "APAC enforcement comparison covering ASIC, MAS, SEBI, HKMA, SFC and SESC themes for AML, market abuse, operational risk, governance and consumer protection.",
    "category": "Regional Benchmark",
    "date": "18 May 2026",
    "dateISO": "2026-05-18"
  },
  {
    "slug": "eu-financial-regulators-enforcement-guide",
    "title": "EU Financial Enforcement: BaFin, AMF, CNMV and CBI",
    "excerpt": "EU financial enforcement guide comparing BaFin, AMF, CNMV, CBI and the EU supervisory architecture for banks, markets, AML, governance and cross-border compliance.",
    "category": "Regional Benchmark",
    "date": "15 May 2026",
    "dateISO": "2026-05-15"
  },
  {
    "slug": "global-aml-enforcement-comparison-2026",
    "title": "Global AML Enforcement Comparison 2026: FCA, FinCEN, AUSTRAC and MAS",
    "excerpt": "Global AML enforcement comparison for 2026 covering CDD, transaction monitoring, SAR governance, sanctions screening, board evidence and remediation across major regulators.",
    "category": "Thematic Analysis",
    "date": "13 May 2026",
    "dateISO": "2026-05-13"
  },
  {
    "slug": "occ-enforcement-actions-complete-guide",
    "title": "OCC Enforcement Actions: Banking Penalties Guide",
    "excerpt": "OCC enforcement guide for national banks, federal savings associations, federal branches, unsafe practices, BSA/AML, fiduciary breaches and board reporting.",
    "category": "Regulatory Guide",
    "date": "11 May 2026",
    "dateISO": "2026-05-11"
  },
  {
    "slug": "sec-enforcement-guide-fines-data",
    "title": "SEC Enforcement Actions: Data and Compliance Guide",
    "excerpt": "SEC enforcement guide covering civil enforcement, litigation releases, administrative proceedings, trading suspensions, harmed investor distributions and compliance monitoring.",
    "category": "Regulatory Guide",
    "date": "8 May 2026",
    "dateISO": "2026-05-08"
  },
  {
    "slug": "fca-fines-enforcement-guide",
    "title": "Financial Conduct Authority (FCA) Fines & Enforcement Guide",
    "excerpt": "Financial Conduct Authority (FCA) enforcement analysis covering 308 tracked actions across 2013-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "bafin-fines-enforcement-guide",
    "title": "Federal Financial Supervisory Authority (BaFin) Fines & Enforcement Guide",
    "excerpt": "Federal Financial Supervisory Authority (BaFin) enforcement analysis covering 246 tracked actions across 2021-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "amf-fines-enforcement-guide",
    "title": "Autorité des marchés financiers (AMF) Fines & Enforcement Guide",
    "excerpt": "Autorité des marchés financiers (AMF) enforcement analysis covering 112 tracked actions across 2023-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cnmv-fines-enforcement-guide",
    "title": "Comisión Nacional del Mercado de Valores (CNMV) Fines & Enforcement Guide",
    "excerpt": "Comisión Nacional del Mercado de Valores (CNMV) enforcement analysis covering 102 tracked actions across 2021-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cbi-fines-enforcement-guide",
    "title": "Central Bank of Ireland (CBI) Fines & Enforcement Guide",
    "excerpt": "Central Bank of Ireland (CBI) enforcement analysis covering 119 tracked actions across 2021-2025. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sfc-fines-enforcement-guide",
    "title": "Securities and Futures Commission (SFC) Fines & Enforcement Guide",
    "excerpt": "Securities and Futures Commission (SFC) enforcement analysis covering 221 tracked actions across 2020-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "afm-fines-enforcement-guide",
    "title": "Authority for the Financial Markets (AFM) Fines & Enforcement Guide",
    "excerpt": "Authority for the Financial Markets (AFM) enforcement analysis covering 7 tracked actions across 2025-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "dnb-fines-enforcement-guide",
    "title": "De Nederlandsche Bank (DNB) Fines & Enforcement Guide",
    "excerpt": "De Nederlandsche Bank (DNB) enforcement analysis covering 48 tracked actions across 2022-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "ciro-fines-enforcement-guide",
    "title": "Canadian Investment Regulatory Organization (CIRO) Fines & Enforcement Guide",
    "excerpt": "Canadian Investment Regulatory Organization (CIRO) enforcement analysis covering 279 tracked actions across 2019-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sec-fines-enforcement-guide",
    "title": "U.S. Securities and Exchange Commission (SEC) Fines & Enforcement Guide",
    "excerpt": "U.S. Securities and Exchange Commission (SEC) enforcement analysis covering 1797 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sebi-fines-enforcement-guide",
    "title": "Securities and Exchange Board of India (SEBI) Fines & Enforcement Guide",
    "excerpt": "Securities and Exchange Board of India (SEBI) enforcement analysis covering 408 tracked actions across 2022-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "twfsc-fines-enforcement-guide",
    "title": "Financial Supervisory Commission (TWFSC) Fines & Enforcement Guide",
    "excerpt": "Financial Supervisory Commission (TWFSC) enforcement analysis covering 924 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cvm-fines-enforcement-guide",
    "title": "Comissão de Valores Mobiliários (CVM) Fines & Enforcement Guide",
    "excerpt": "Comissão de Valores Mobiliários (CVM) enforcement analysis covering 557 tracked actions across 2021-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "hkma-fines-enforcement-guide",
    "title": "Hong Kong Monetary Authority (HKMA) Fines & Enforcement Guide",
    "excerpt": "Hong Kong Monetary Authority (HKMA) enforcement analysis covering 23 tracked actions across 2015-2025. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "asic-fines-enforcement-guide",
    "title": "Australian Securities and Investments Commission (ASIC) Fines & Enforcement Guide",
    "excerpt": "Australian Securities and Investments Commission (ASIC) enforcement analysis covering 112 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "mas-fines-enforcement-guide",
    "title": "Monetary Authority of Singapore (MAS) Fines & Enforcement Guide",
    "excerpt": "Monetary Authority of Singapore (MAS) enforcement analysis covering 21 tracked actions across 2023-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "occ-fines-enforcement-guide",
    "title": "Office of the Comptroller of the Currency (OCC) Fines & Enforcement Guide",
    "excerpt": "Office of the Comptroller of the Currency (OCC) enforcement analysis covering 5579 tracked actions across 1987-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fincen-fines-enforcement-guide",
    "title": "Financial Crimes Enforcement Network (FINCEN) Fines & Enforcement Guide",
    "excerpt": "Financial Crimes Enforcement Network (FINCEN) enforcement analysis covering 118 tracked actions across 1999-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "finma-fines-enforcement-guide",
    "title": "Swiss Financial Market Supervisory Authority (FINMA) Fines & Enforcement Guide",
    "excerpt": "Swiss Financial Market Supervisory Authority (FINMA) enforcement analysis covering 26 tracked actions across 2018-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sesc-fines-enforcement-guide",
    "title": "Securities and Exchange Surveillance Commission (SESC) Fines & Enforcement Guide",
    "excerpt": "Securities and Exchange Surveillance Commission (SESC) enforcement analysis covering 66 tracked actions across 2023-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fmanz-fines-enforcement-guide",
    "title": "Financial Markets Authority (FMANZ) Fines & Enforcement Guide",
    "excerpt": "Financial Markets Authority (FMANZ) enforcement analysis covering 99 tracked actions across 2015-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "frb-fines-enforcement-guide",
    "title": "Federal Reserve Board (FRB) Fines & Enforcement Guide",
    "excerpt": "Federal Reserve Board (FRB) enforcement analysis covering 2882 tracked actions across 1989-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "osc-fines-enforcement-guide",
    "title": "Ontario Securities Commission (OSC) Fines & Enforcement Guide",
    "excerpt": "Ontario Securities Commission (OSC) enforcement analysis covering 653 tracked actions across 2003-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "austrac-fines-enforcement-guide",
    "title": "Australian Transaction Reports and Analysis Centre (AUSTRAC) Fines & Enforcement Guide",
    "excerpt": "Australian Transaction Reports and Analysis Centre (AUSTRAC) enforcement analysis covering 70 tracked actions across 2009-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fca-fines-insurance-sector",
    "title": "FCA Fines for Insurance Companies: Complete Sector Analysis",
    "excerpt": "Comprehensive analysis of FCA fines against insurance companies. Covers general insurers, life insurers, brokers, and Lloyd's market participants — including penalty amounts, breach types, and regulatory trends.",
    "category": "Sector Analysis",
    "date": "March 2026",
    "dateISO": "2026-03-16"
  },
  {
    "slug": "fca-fines-march-2026",
    "title": "FCA Fines March 2026: Market Disclosure and Controls",
    "excerpt": "March 2026 FCA fines guide covering John Wood Group, Dinosaur Merchant Bank, misleading information, market abuse systems and board control evidence.",
    "category": "FCA Fines 2026",
    "date": "March 2026",
    "dateISO": "2026-03-01"
  },
  {
    "slug": "fca-fines-individuals-personal-accountability",
    "title": "FCA Fines for Individuals: Personal Accountability & Penalties",
    "excerpt": "Complete analysis of FCA fines against individuals. Covers personal liability under SM&CR, prohibition orders, financial penalties, and how the FCA holds individuals accountable.",
    "category": "Regulatory Guide",
    "date": "February 2026",
    "dateISO": "2026-02-16"
  },
  {
    "slug": "fca-enforcement-outlook-february-2026",
    "title": "FCA Enforcement Outlook 2026: What Boards Should Watch",
    "excerpt": "FCA enforcement outlook for 2026 covering individual accountability, market disclosure, financial crime, operational resilience and board evidence.",
    "category": "Trends Analysis",
    "date": "February 2026",
    "dateISO": "2026-02-10"
  },
  {
    "slug": "fca-fines-february-2026",
    "title": "FCA Fines February 2026: Market Disclosure and Governance",
    "excerpt": "February 2026 FCA fines guide covering market disclosure, Carillion-related findings, governance evidence, final notice interpretation and board reporting.",
    "category": "FCA Fines 2026",
    "date": "February 2026",
    "dateISO": "2026-02-01"
  },
  {
    "slug": "fca-fines-january-2026",
    "title": "FCA Fines January 2026: Individual Accountability Guide",
    "excerpt": "January 2026 FCA fines guide covering individual accountability, market abuse, insider dealing, Carillion-related findings, board evidence and senior manager read-across.",
    "category": "FCA Fines 2026",
    "date": "January 2026",
    "dateISO": "2026-01-31"
  },
  {
    "slug": "fca-fines-2025-complete-list",
    "title": "FCA Fines 2025: Complete List of All Penalties This Year",
    "excerpt": "Track all FCA fines issued in 2025. Updated list includes Nationwide £44m, Barclays £39m, and all enforcement actions. See total fines and trends.",
    "category": "FCA Fines 2025",
    "date": "January 2025",
    "dateISO": "2025-01-18"
  },
  {
    "slug": "20-biggest-fca-fines-of-all-time",
    "title": "20 Biggest FCA Fines: Enforcement Lessons for Boards",
    "excerpt": "Guide to the 20 biggest FCA fines, with board-level lessons on AML, market abuse, FX, banking controls, remediation evidence and senior accountability.",
    "category": "FCA Fines List",
    "date": "January 2025",
    "dateISO": "2025-01-15"
  },
  {
    "slug": "fca-enforcement-trends-2013-2025",
    "title": "FCA Enforcement Trends 2013-2025: Fines and Controls",
    "excerpt": "Long-run FCA enforcement trend guide covering fines, AML, market abuse, Consumer Duty, operational resilience, senior accountability and board monitoring.",
    "category": "Trends Analysis",
    "date": "January 2025",
    "dateISO": "2025-01-12"
  },
  {
    "slug": "fca-fines-database-how-to-search",
    "title": "How to Search the FCA Fines Database: A Practical Guide",
    "excerpt": "A practical guide to searching FCA enforcement actions by firm, year, breach and amount, with links to the live database and official final notices.",
    "category": "Database Guide",
    "date": "January 2025",
    "dateISO": "2025-01-10"
  },
  {
    "slug": "fca-aml-fines-anti-money-laundering",
    "title": "FCA AML Fines: Anti-Money Laundering Enforcement Guide",
    "excerpt": "FCA AML fines guide covering financial crime controls, CDD, transaction monitoring, sanctions, SAR escalation, governance and board remediation evidence.",
    "category": "AML Fines",
    "date": "December 2024",
    "dateISO": "2024-12-20"
  },
  {
    "slug": "fca-fines-banks-complete-list",
    "title": "FCA Fines to Banks: Banking Enforcement and AML Guide",
    "excerpt": "Guide to FCA banking fines covering AML, financial crime, market conduct, operational controls, governance, senior manager evidence and board reporting.",
    "category": "Banking Fines",
    "date": "November 2024",
    "dateISO": "2024-11-15"
  },
  {
    "slug": "fca-final-notices-explained",
    "title": "FCA Final Notices Explained: Enforcement Decision Guide",
    "excerpt": "Guide to FCA final notices, decision notices, warning notices, supervisory notices and how compliance teams should turn enforcement decisions into board evidence.",
    "category": "Regulatory Guide",
    "date": "October 2024",
    "dateISO": "2024-10-25"
  },
  {
    "slug": "senior-managers-regime-fca-fines",
    "title": "Senior Managers Regime: FCA Fines and Accountability",
    "excerpt": "Guide to SMCR, FCA fines and senior manager accountability covering reasonable steps, conduct rules, certification, board evidence and enforcement read-across.",
    "category": "SM&CR",
    "date": "September 2024",
    "dateISO": "2024-09-18"
  }
];

/** Total published articles, for "all N insights" style counts. */
export const BLOG_ARTICLE_COUNT = 71;
