/** GENERATED by scripts/generate-blog-index.ts. Do not edit by hand. */

/**
 * Card-sized article metadata for surfaces that list articles without reading
 * them. Importing blogArticles.ts pulls in every article body; this does not.
 */
export interface BlogArticleCard {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  dateISO: string;
}

/** Published articles, newest first. */
export const BLOG_ARTICLE_INDEX: BlogArticleCard[] = [
  {
    "slug": "cyber-operational-resilience-enforcement",
    "title": "Cyber and Operational Resilience: Escalating Enforcement Actions",
    "excerpt": "Regulators are increasingly imposing penalties for failures in cyber controls, operational integrity, and financial reporting.",
    "category": "Enforcement Analysis",
    "date": "16 September 2026",
    "dateISO": "2026-09-16"
  },
  {
    "slug": "regulatory-roundup-september-2026",
    "title": "Regulatory Roundup: September 2026 Enforcement Actions Analysed",
    "excerpt": "An analysis of 19 global enforcement actions from September 2026 reveals a focus on organisational failures, disclosure breaches, and supervisory defiance.",
    "category": "Enforcement Roundup",
    "date": "14 September 2026",
    "dateISO": "2026-09-14"
  },
  {
    "slug": "consumer-protection-conduct-risk",
    "title": "Consumer Protection Enforcement: Persistent Conduct Risk Identified",
    "excerpt": "Regulatory enforcement data reveals persistent conduct risk across banking, insurance, and brokerage sectors. Failures in fee transparency, suitability, and customer communications trigger penalties, cancellations.",
    "category": "Enforcement Analysis",
    "date": "2 September 2026",
    "dateISO": "2026-09-02"
  },
  {
    "slug": "enforcement-weekly-2026-w36",
    "title": "Global Enforcement: Reporting Failures and Individual Accountability",
    "excerpt": "Analysis of 23 enforcement actions from seven regulators reveals a focus on reporting failures, cross-border conduct, and individual accountability.",
    "category": "Enforcement Roundup",
    "date": "31 August 2026",
    "dateISO": "2026-08-31"
  },
  {
    "slug": "market-abuse-insider-dealing-analysis",
    "title": "Market Abuse and Insider Dealing: A Cross-Jurisdictional Analysis",
    "excerpt": "An analysis of 30 recent enforcement actions reveals a global regulatory focus on market abuse, targeting individuals and firms for insider dealing, disclosure failures, and inadequate controls.",
    "category": "Enforcement Analysis",
    "date": "26 August 2026",
    "dateISO": "2026-08-26"
  },
  {
    "slug": "enforcement-spotlight-2026-w34",
    "title": "Enforcement Spotlight: Individual Accountability and Fraud Prevention",
    "excerpt": "Recent regulatory actions highlight a persistent focus on individual accountability, fraud in opaque markets, and procedural enforcement across multiple jurisdictions.",
    "category": "Enforcement Roundup",
    "date": "17 August 2026",
    "dateISO": "2026-08-17"
  },
  {
    "slug": "aml-kyc-enforcement-trends",
    "title": "Global AML Enforcement: Key Trends and Regulatory Expectations",
    "excerpt": "Analysis of 30 recent enforcement actions reveals a global regulatory focus on Anti-Money Laundering (AML) programme failures, with significant penalties for inadequate transaction monitoring and customer due diligence.",
    "category": "Enforcement Analysis",
    "date": "12 August 2026",
    "dateISO": "2026-08-12"
  },
  {
    "slug": "enforcement-weekly-2026-w33",
    "title": "Global Enforcement: AML, Reporting, and Conduct Penalties (27 July-10 August)",
    "excerpt": "This analysis covers 12 global enforcement actions from 27 July to 10 August 2026, including a USD 20 million AML fine for UBS, a German financial reporting penalty, and diverse sanctions from SEBI, BaFin, and CIRO.",
    "category": "Enforcement Roundup",
    "date": "10 August 2026",
    "dateISO": "2026-08-10"
  },
  {
    "slug": "board-guide-aml-controls",
    "title": "Board Guide: Building Effective AML Controls",
    "excerpt": "Recent enforcement actions reveal systemic Anti-Money Laundering (AML) control failures. Boards must move beyond policy to ensure risk-based monitoring, independent testing.",
    "category": "Board Governance",
    "date": "7 August 2026",
    "dateISO": "2026-08-07"
  },
  {
    "slug": "regulatory-roundup-august-2026",
    "title": "July 2026 Enforcement Actions: A Regulatory Analysis",
    "excerpt": "Global regulators issued 16 public enforcement actions in July 2026. This analysis examines key cases from FINRA, BaFin, and SEBI, highlighting critical compliance and operational failures across jurisdictions.",
    "category": "Enforcement Roundup",
    "date": "3 August 2026",
    "dateISO": "2026-08-03"
  },
  {
    "slug": "fca-fines-july-2025",
    "title": "FCA Final Notices: July 2025 Enforcement Actions Analysed",
    "excerpt": "This report reviews nine FCA final notices from July 2025, covering governance, AML, reporting, and controls. Only source-verified monetary amounts are included, ensuring an evidence-led analysis of enforcement outcomes.",
    "category": "FCA Fines 2025",
    "date": "24 July 2026",
    "dateISO": "2026-07-24"
  },
  {
    "slug": "state-of-global-aml-enforcement-h1-2026",
    "title": "State of Global AML Enforcement: H1 2026",
    "excerpt": "A data study built from RegActions' live enforcement and country-risk APIs: the H1 2026 regulator league table, breach trends, FCA fines up 41% year on year, and the June FATF plenary. Free to reuse under CC BY-NC 4.0.",
    "category": "Data Studies",
    "date": "July 2026",
    "dateISO": "2026-07-17"
  },
  {
    "slug": "wealth-managers-consumer-duty-enforcement",
    "title": "Wealth Managers: Why You're at the Front of the Consumer Duty Queue",
    "excerpt": "Wealth managers carry four pre-existing risk concentrations that map directly onto the Consumer Duty's four outcomes — fees, complexity, ageing client demographics, and vertical integration. That alignment makes the sector the highest-probability source of the first wave of Consumer Duty enforcement. Here's why, what the existing enforcement record shows, and what wealth-firm boards should be doing now.",
    "category": "Sector Analysis",
    "date": "July 2026",
    "dateISO": "2026-07-05"
  },
  {
    "slug": "consumer-duty-three-years-enforcement",
    "title": "Consumer Duty Enforcement: Three Years In, Where the FCA May Act Next",
    "excerpt": "Consumer Duty enforcement guide covering customer outcomes, fair value, advice, wealth management, board MI, vulnerability, remediation and FCA evidence expectations.",
    "category": "Thematic Analysis",
    "date": "July 2026",
    "dateISO": "2026-07-03"
  },
  {
    "slug": "fca-fines-enforcement-guide",
    "title": "Financial Conduct Authority (FCA) Fines & Enforcement Guide",
    "excerpt": "Financial Conduct Authority (FCA) enforcement analysis covering 308 tracked actions across 2013-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "bafin-fines-enforcement-guide",
    "title": "Federal Financial Supervisory Authority (BaFin) Fines & Enforcement Guide",
    "excerpt": "Federal Financial Supervisory Authority (BaFin) enforcement analysis covering 246 tracked actions across 2021-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "amf-fines-enforcement-guide",
    "title": "Autorité des marchés financiers (AMF) Fines & Enforcement Guide",
    "excerpt": "Autorité des marchés financiers (AMF) enforcement analysis covering 112 tracked actions across 2023-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cnmv-fines-enforcement-guide",
    "title": "Comisión Nacional del Mercado de Valores (CNMV) Fines & Enforcement Guide",
    "excerpt": "Comisión Nacional del Mercado de Valores (CNMV) enforcement analysis covering 102 tracked actions across 2021-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cbi-fines-enforcement-guide",
    "title": "Central Bank of Ireland (CBI) Fines & Enforcement Guide",
    "excerpt": "Central Bank of Ireland (CBI) enforcement analysis covering 119 tracked actions across 2021-2025. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sfc-fines-enforcement-guide",
    "title": "Securities and Futures Commission (SFC) Fines & Enforcement Guide",
    "excerpt": "Securities and Futures Commission (SFC) enforcement analysis covering 221 tracked actions across 2020-2026. Covers public source structure, enforcement priorities, and practical monitoring takeaways for compliance teams.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "afm-fines-enforcement-guide",
    "title": "Authority for the Financial Markets (AFM) Fines & Enforcement Guide",
    "excerpt": "Authority for the Financial Markets (AFM) enforcement analysis covering 7 tracked actions across 2025-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "dnb-fines-enforcement-guide",
    "title": "De Nederlandsche Bank (DNB) Fines & Enforcement Guide",
    "excerpt": "De Nederlandsche Bank (DNB) enforcement analysis covering 48 tracked actions across 2023-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "ciro-fines-enforcement-guide",
    "title": "Canadian Investment Regulatory Organization (CIRO) Fines & Enforcement Guide",
    "excerpt": "Canadian Investment Regulatory Organization (CIRO) enforcement analysis covering 279 tracked actions across 2019-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sec-fines-enforcement-guide",
    "title": "U.S. Securities and Exchange Commission (SEC) Fines & Enforcement Guide",
    "excerpt": "U.S. Securities and Exchange Commission (SEC) enforcement analysis covering 1797 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sebi-fines-enforcement-guide",
    "title": "Securities and Exchange Board of India (SEBI) Fines & Enforcement Guide",
    "excerpt": "Securities and Exchange Board of India (SEBI) enforcement analysis covering 408 tracked actions across 2022-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "twfsc-fines-enforcement-guide",
    "title": "Financial Supervisory Commission (TWFSC) Fines & Enforcement Guide",
    "excerpt": "Financial Supervisory Commission (TWFSC) enforcement analysis covering 924 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cvm-fines-enforcement-guide",
    "title": "Comissão de Valores Mobiliários (CVM) Fines & Enforcement Guide",
    "excerpt": "Comissão de Valores Mobiliários (CVM) enforcement analysis covering 557 tracked actions across 2021-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "cnbv-fines-enforcement-guide",
    "title": "Comisión Nacional Bancaria y de Valores (CNBV) Fines & Enforcement Guide",
    "excerpt": "Comisión Nacional Bancaria y de Valores (CNBV) enforcement analysis covering 11206 tracked actions across 2017-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "hkma-fines-enforcement-guide",
    "title": "Hong Kong Monetary Authority (HKMA) Fines & Enforcement Guide",
    "excerpt": "Hong Kong Monetary Authority (HKMA) enforcement analysis covering 23 tracked actions across 2015-2025. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "asic-fines-enforcement-guide",
    "title": "Australian Securities and Investments Commission (ASIC) Fines & Enforcement Guide",
    "excerpt": "Australian Securities and Investments Commission (ASIC) enforcement analysis covering 112 tracked actions across 2012-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "mas-fines-enforcement-guide",
    "title": "Monetary Authority of Singapore (MAS) Fines & Enforcement Guide",
    "excerpt": "Monetary Authority of Singapore (MAS) enforcement analysis covering 21 tracked actions across 2023-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "occ-fines-enforcement-guide",
    "title": "Office of the Comptroller of the Currency (OCC) Fines & Enforcement Guide",
    "excerpt": "Office of the Comptroller of the Currency (OCC) enforcement analysis covering 5579 tracked actions across 1987-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fincen-fines-enforcement-guide",
    "title": "Financial Crimes Enforcement Network (FINCEN) Fines & Enforcement Guide",
    "excerpt": "Financial Crimes Enforcement Network (FINCEN) enforcement analysis covering 118 tracked actions across 1999-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "finma-fines-enforcement-guide",
    "title": "Swiss Financial Market Supervisory Authority (FINMA) Fines & Enforcement Guide",
    "excerpt": "Swiss Financial Market Supervisory Authority (FINMA) enforcement analysis covering 26 tracked actions across 2018-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "sesc-fines-enforcement-guide",
    "title": "Securities and Exchange Surveillance Commission (SESC) Fines & Enforcement Guide",
    "excerpt": "Securities and Exchange Surveillance Commission (SESC) enforcement analysis covering 66 tracked actions across 2023-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fsca-fines-enforcement-guide",
    "title": "Financial Sector Conduct Authority (FSCA) Fines & Enforcement Guide",
    "excerpt": "Financial Sector Conduct Authority (FSCA) enforcement analysis covering 576 tracked actions across 2006-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fmanz-fines-enforcement-guide",
    "title": "Financial Markets Authority (FMANZ) Fines & Enforcement Guide",
    "excerpt": "Financial Markets Authority (FMANZ) enforcement analysis covering 99 tracked actions across 2015-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "frb-fines-enforcement-guide",
    "title": "Federal Reserve Board (FRB) Fines & Enforcement Guide",
    "excerpt": "Federal Reserve Board (FRB) enforcement analysis covering 2882 tracked actions across 1989-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "osc-fines-enforcement-guide",
    "title": "Ontario Securities Commission (OSC) Fines & Enforcement Guide",
    "excerpt": "Ontario Securities Commission (OSC) enforcement analysis covering 653 tracked actions across 2003-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "austrac-fines-enforcement-guide",
    "title": "Australian Transaction Reports and Analysis Centre (AUSTRAC) Fines & Enforcement Guide",
    "excerpt": "Australian Transaction Reports and Analysis Centre (AUSTRAC) enforcement analysis covering 70 tracked actions across 2009-2026. Includes candid coverage notes on source shape, dataset strength, and how to use the feed in compliance monitoring.",
    "category": "Regulatory Intelligence",
    "date": "March 2026",
    "dateISO": "2026-03-27T00:00:00.000Z"
  },
  {
    "slug": "fca-fines-insurance-sector",
    "title": "FCA Fines for Insurance Companies: Complete Sector Analysis",
    "excerpt": "Comprehensive analysis of FCA fines against insurance companies. Covers general insurers, life insurers, brokers, and Lloyd's market participants — including penalty amounts, breach types, and regulatory trends.",
    "category": "Sector Analysis",
    "date": "March 2026",
    "dateISO": "2026-03-16"
  },
  {
    "slug": "fca-fines-march-2026",
    "title": "FCA Fines March 2026: Market Disclosure and Controls",
    "excerpt": "March 2026 FCA fines guide covering John Wood Group, Dinosaur Merchant Bank, misleading information, market abuse systems and board control evidence.",
    "category": "FCA Fines 2026",
    "date": "March 2026",
    "dateISO": "2026-03-01"
  },
  {
    "slug": "fca-fines-individuals-personal-accountability",
    "title": "FCA Fines for Individuals: Personal Accountability & Penalties",
    "excerpt": "Complete analysis of FCA fines against individuals. Covers personal liability under SM&CR, prohibition orders, financial penalties, and how the FCA holds individuals accountable.",
    "category": "Regulatory Guide",
    "date": "February 2026",
    "dateISO": "2026-02-16"
  },
  {
    "slug": "fca-enforcement-outlook-february-2026",
    "title": "FCA Enforcement Outlook 2026: What Boards Should Watch",
    "excerpt": "FCA enforcement outlook for 2026 covering individual accountability, market disclosure, financial crime, operational resilience and board evidence.",
    "category": "Trends Analysis",
    "date": "February 2026",
    "dateISO": "2026-02-10"
  },
  {
    "slug": "fca-fines-february-2026",
    "title": "FCA Fines February 2026: Market Disclosure and Governance",
    "excerpt": "February 2026 FCA fines guide covering market disclosure, Carillion-related findings, governance evidence, final notice interpretation and board reporting.",
    "category": "FCA Fines 2026",
    "date": "February 2026",
    "dateISO": "2026-02-01"
  },
  {
    "slug": "fca-fines-january-2026",
    "title": "FCA Fines January 2026: Individual Accountability Guide",
    "excerpt": "January 2026 FCA fines guide covering individual accountability, market abuse, insider dealing, Carillion-related findings, board evidence and senior manager read-across.",
    "category": "FCA Fines 2026",
    "date": "January 2026",
    "dateISO": "2026-01-31"
  },
  {
    "slug": "fca-fines-2025-complete-list",
    "title": "FCA Fines 2025: Complete List of All Penalties This Year",
    "excerpt": "Track all FCA fines issued in 2025. Updated list includes Nationwide £44m, Barclays £39m, and all enforcement actions. See total fines and trends.",
    "category": "FCA Fines 2025",
    "date": "January 2025",
    "dateISO": "2025-01-18"
  },
  {
    "slug": "20-biggest-fca-fines-of-all-time",
    "title": "20 Biggest FCA Fines: Enforcement Lessons for Boards",
    "excerpt": "Guide to the 20 biggest FCA fines, with board-level lessons on AML, market abuse, FX, banking controls, remediation evidence and senior accountability.",
    "category": "FCA Fines List",
    "date": "January 2025",
    "dateISO": "2025-01-15"
  },
  {
    "slug": "fca-enforcement-trends-2013-2025",
    "title": "FCA Enforcement Trends 2013-2025: Fines and Controls",
    "excerpt": "Long-run FCA enforcement trend guide covering fines, AML, market abuse, Consumer Duty, operational resilience, senior accountability and board monitoring.",
    "category": "Trends Analysis",
    "date": "January 2025",
    "dateISO": "2025-01-12"
  },
  {
    "slug": "fca-fines-database-how-to-search",
    "title": "How to Search the FCA Fines Database: A Practical Guide",
    "excerpt": "A practical guide to searching FCA enforcement actions by firm, year, breach and amount, with links to the live database and official final notices.",
    "category": "Database Guide",
    "date": "January 2025",
    "dateISO": "2025-01-10"
  },
  {
    "slug": "fca-aml-fines-anti-money-laundering",
    "title": "FCA AML Fines: Anti-Money Laundering Enforcement Guide",
    "excerpt": "FCA AML fines guide covering financial crime controls, CDD, transaction monitoring, sanctions, SAR escalation, governance and board remediation evidence.",
    "category": "AML Fines",
    "date": "December 2024",
    "dateISO": "2024-12-20"
  },
  {
    "slug": "fca-fines-banks-complete-list",
    "title": "FCA Fines to Banks: Banking Enforcement and AML Guide",
    "excerpt": "Guide to FCA banking fines covering AML, financial crime, market conduct, operational controls, governance, senior manager evidence and board reporting.",
    "category": "Banking Fines",
    "date": "November 2024",
    "dateISO": "2024-11-15"
  },
  {
    "slug": "fca-final-notices-explained",
    "title": "FCA Final Notices Explained: Enforcement Decision Guide",
    "excerpt": "Guide to FCA final notices, decision notices, warning notices, supervisory notices and how compliance teams should turn enforcement decisions into board evidence.",
    "category": "Regulatory Guide",
    "date": "October 2024",
    "dateISO": "2024-10-25"
  },
  {
    "slug": "senior-managers-regime-fca-fines",
    "title": "Senior Managers Regime: FCA Fines and Accountability",
    "excerpt": "Guide to SMCR, FCA fines and senior manager accountability covering reasonable steps, conduct rules, certification, board evidence and enforcement read-across.",
    "category": "SM&CR",
    "date": "September 2024",
    "dateISO": "2024-09-18"
  }
];

/** Total published articles, for "all N insights" style counts. */
export const BLOG_ARTICLE_COUNT = 54;
