/**
 * Transparency International — Corruption Perceptions Index (CPI) snapshot.
 *
 * Score 0–100 (HIGHER = cleaner / less corrupt) + rank (1 = cleanest) within the
 * 2024 table (179 countries ranked; standard-competition ranking).
 *
 * DISPLAY-ONLY. CPI is licensed CC BY-ND: we show it unmodified and NEVER feed it
 * into the RegActions Country Risk Score (the scored corruption signal comes from
 * the World Bank WGI Control-of-Corruption dimension). Attribution required.
 *
 * GENERATED by scripts/ingest-cpi.ts. Do not edit by hand — re-run to refresh.
 */

export const CPI_YEAR = "2024";
export const CPI_TOTAL = 179;
export const CPI_SOURCE = "https://www.transparency.org/en/cpi/2024";
export const CPI_LICENCE = "CC BY-ND 4.0 — Transparency International";

export interface CpiEntry {
  /** 0–100, higher = cleaner. */
  score: number;
  /** 1 = cleanest; out of CPI_TOTAL. */
  rank: number;
}

/** iso2 -> CPI score + rank (2024). Display only, never scored. */
export const CPI_RANK: Record<string, CpiEntry> = {
  DK: { score: 90, rank: 1 }, // Denmark
  FI: { score: 88, rank: 2 }, // Finland
  SG: { score: 84, rank: 3 }, // Singapore
  NZ: { score: 83, rank: 4 }, // New Zealand
  LU: { score: 81, rank: 5 }, // Luxembourg
  NO: { score: 81, rank: 5 }, // Norway
  CH: { score: 81, rank: 5 }, // Switzerland
  SE: { score: 80, rank: 8 }, // Sweden
  NL: { score: 78, rank: 9 }, // Netherlands
  AU: { score: 77, rank: 10 }, // Australia
  IS: { score: 77, rank: 10 }, // Iceland
  IE: { score: 77, rank: 10 }, // Ireland
  EE: { score: 76, rank: 13 }, // Estonia
  UY: { score: 76, rank: 13 }, // Uruguay
  CA: { score: 75, rank: 15 }, // Canada
  DE: { score: 75, rank: 15 }, // Germany
  HK: { score: 74, rank: 17 }, // Hong Kong
  BT: { score: 72, rank: 18 }, // Bhutan
  SC: { score: 72, rank: 18 }, // Seychelles
  JP: { score: 71, rank: 20 }, // Japan
  GB: { score: 71, rank: 20 }, // United Kingdom
  BE: { score: 69, rank: 22 }, // Belgium
  BB: { score: 68, rank: 23 }, // Barbados
  AE: { score: 68, rank: 23 }, // United Arab Emirates
  AT: { score: 67, rank: 25 }, // Austria
  FR: { score: 67, rank: 25 }, // France
  TW: { score: 67, rank: 25 }, // Taiwan
  BS: { score: 65, rank: 28 }, // Bahamas
  US: { score: 65, rank: 28 }, // United States
  IL: { score: 64, rank: 30 }, // Israel
  KR: { score: 64, rank: 30 }, // South Korea
  CL: { score: 63, rank: 32 }, // Chile
  LT: { score: 63, rank: 32 }, // Lithuania
  CV: { score: 62, rank: 35 }, // Cabo Verde
  SI: { score: 60, rank: 36 }, // Slovenia
  LV: { score: 59, rank: 38 }, // Latvia
  QA: { score: 59, rank: 38 }, // Qatar
  SA: { score: 59, rank: 38 }, // Saudi Arabia
  CR: { score: 58, rank: 42 }, // Costa Rica
  BW: { score: 57, rank: 43 }, // Botswana
  PT: { score: 57, rank: 43 }, // Portugal
  RW: { score: 57, rank: 43 }, // Rwanda
  CY: { score: 56, rank: 46 }, // Cyprus
  CZ: { score: 56, rank: 46 }, // Czechia
  ES: { score: 56, rank: 46 }, // Spain
  FJ: { score: 55, rank: 50 }, // Fiji
  OM: { score: 55, rank: 50 }, // Oman
  IT: { score: 54, rank: 52 }, // Italy
  BH: { score: 53, rank: 53 }, // Bahrain
  PL: { score: 53, rank: 53 }, // Poland
  MU: { score: 51, rank: 56 }, // Mauritius
  MY: { score: 50, rank: 57 }, // Malaysia
  VU: { score: 50, rank: 57 }, // Vanuatu
  GR: { score: 49, rank: 59 }, // Greece
  JO: { score: 49, rank: 59 }, // Jordan
  NA: { score: 49, rank: 59 }, // Namibia
  SK: { score: 49, rank: 59 }, // Slovakia
  HR: { score: 47, rank: 63 }, // Croatia
  KW: { score: 46, rank: 65 }, // Kuwait
  MT: { score: 46, rank: 65 }, // Malta
  ME: { score: 46, rank: 65 }, // Montenegro
  RO: { score: 46, rank: 65 }, // Romania
  BJ: { score: 45, rank: 69 }, // Benin
  CI: { score: 45, rank: 69 }, // Côte d'Ivoire
  ST: { score: 45, rank: 69 }, // São Tomé and Príncipe
  SN: { score: 45, rank: 69 }, // Senegal
  JM: { score: 44, rank: 73 }, // Jamaica
  TL: { score: 44, rank: 73 }, // Timor-Leste
  BG: { score: 43, rank: 75 }, // Bulgaria
  CN: { score: 43, rank: 75 }, // China
  MD: { score: 43, rank: 75 }, // Moldova
  AL: { score: 42, rank: 79 }, // Albania
  GH: { score: 42, rank: 79 }, // Ghana
  BF: { score: 41, rank: 81 }, // Burkina Faso
  CU: { score: 41, rank: 81 }, // Cuba
  HU: { score: 41, rank: 81 }, // Hungary
  ZA: { score: 41, rank: 81 }, // South Africa
  TZ: { score: 41, rank: 81 }, // Tanzania
  TT: { score: 41, rank: 81 }, // Trinidad and Tobago
  KZ: { score: 40, rank: 87 }, // Kazakhstan
  MK: { score: 40, rank: 87 }, // North Macedonia
  SR: { score: 40, rank: 87 }, // Suriname
  VN: { score: 40, rank: 87 }, // Vietnam
  CO: { score: 39, rank: 91 }, // Colombia
  GY: { score: 39, rank: 91 }, // Guyana
  TN: { score: 39, rank: 91 }, // Tunisia
  ZM: { score: 39, rank: 91 }, // Zambia
  IN: { score: 38, rank: 95 }, // India
  MV: { score: 38, rank: 95 }, // Maldives
  GM: { score: 38, rank: 95 }, // The Gambia
  AR: { score: 37, rank: 98 }, // Argentina
  ET: { score: 37, rank: 98 }, // Ethiopia
  ID: { score: 37, rank: 98 }, // Indonesia
  LS: { score: 37, rank: 98 }, // Lesotho
  MA: { score: 37, rank: 98 }, // Morocco
  DO: { score: 36, rank: 103 }, // Dominican Republic
  RS: { score: 35, rank: 104 }, // Serbia
  UA: { score: 35, rank: 104 }, // Ukraine
  DZ: { score: 34, rank: 106 }, // Algeria
  BR: { score: 34, rank: 106 }, // Brazil
  MW: { score: 34, rank: 106 }, // Malawi
  NP: { score: 34, rank: 106 }, // Nepal
  NE: { score: 34, rank: 106 }, // Niger
  TH: { score: 34, rank: 106 }, // Thailand
  TR: { score: 34, rank: 106 }, // Türkiye
  BY: { score: 33, rank: 113 }, // Belarus
  BA: { score: 33, rank: 113 }, // Bosnia and Herzegovina
  LA: { score: 33, rank: 113 }, // Laos
  MN: { score: 33, rank: 113 }, // Mongolia
  PA: { score: 33, rank: 113 }, // Panama
  PH: { score: 33, rank: 113 }, // Philippines
  SL: { score: 33, rank: 113 }, // Sierra Leone
  AO: { score: 32, rank: 120 }, // Angola
  EC: { score: 32, rank: 120 }, // Ecuador
  KE: { score: 32, rank: 120 }, // Kenya
  LK: { score: 32, rank: 120 }, // Sri Lanka
  TG: { score: 32, rank: 120 }, // Togo
  UZ: { score: 32, rank: 120 }, // Uzbekistan
  DJ: { score: 31, rank: 126 }, // Djibouti
  PG: { score: 31, rank: 126 }, // Papua New Guinea
  PE: { score: 31, rank: 126 }, // Peru
  EG: { score: 30, rank: 129 }, // Egypt
  SV: { score: 30, rank: 129 }, // El Salvador
  MR: { score: 30, rank: 129 }, // Mauritania
  BO: { score: 28, rank: 132 }, // Bolivia
  GN: { score: 28, rank: 132 }, // Guinea
  SZ: { score: 27, rank: 134 }, // Eswatini
  GA: { score: 27, rank: 134 }, // Gabon
  LR: { score: 27, rank: 134 }, // Liberia
  ML: { score: 27, rank: 134 }, // Mali
  PK: { score: 27, rank: 134 }, // Pakistan
  CM: { score: 26, rank: 139 }, // Cameroon
  IQ: { score: 26, rank: 139 }, // Iraq
  MG: { score: 26, rank: 139 }, // Madagascar
  MX: { score: 26, rank: 139 }, // Mexico
  NG: { score: 26, rank: 139 }, // Nigeria
  UG: { score: 26, rank: 139 }, // Uganda
  GT: { score: 25, rank: 145 }, // Guatemala
  KG: { score: 25, rank: 145 }, // Kyrgyzstan
  MZ: { score: 25, rank: 145 }, // Mozambique
  CF: { score: 24, rank: 148 }, // Central African Republic
  PY: { score: 24, rank: 148 }, // Paraguay
  BD: { score: 23, rank: 150 }, // Bangladesh
  IR: { score: 23, rank: 150 }, // Iran
  CG: { score: 23, rank: 150 }, // Republic of the Congo
  HN: { score: 22, rank: 153 }, // Honduras
  LB: { score: 22, rank: 153 }, // Lebanon
  RU: { score: 22, rank: 153 }, // Russia
  KH: { score: 21, rank: 157 }, // Cambodia
  TD: { score: 21, rank: 157 }, // Chad
  KM: { score: 21, rank: 157 }, // Comoros
  GW: { score: 21, rank: 157 }, // Guinea-Bissau
  ZW: { score: 21, rank: 157 }, // Zimbabwe
  CD: { score: 20, rank: 162 }, // Democratic Republic of the Congo
  TJ: { score: 19, rank: 163 }, // Tajikistan
  AF: { score: 17, rank: 164 }, // Afghanistan
  BI: { score: 17, rank: 164 }, // Burundi
  TM: { score: 17, rank: 164 }, // Turkmenistan
  HT: { score: 16, rank: 167 }, // Haiti
  MM: { score: 16, rank: 167 }, // Myanmar
  KP: { score: 15, rank: 169 }, // North Korea
  SD: { score: 15, rank: 169 }, // Sudan
  NI: { score: 14, rank: 171 }, // Nicaragua
  GQ: { score: 13, rank: 172 }, // Equatorial Guinea
  ER: { score: 13, rank: 172 }, // Eritrea
  LY: { score: 13, rank: 172 }, // Libya
  YE: { score: 13, rank: 172 }, // Yemen
  SY: { score: 12, rank: 176 }, // Syria
  VE: { score: 10, rank: 177 }, // Venezuela
  SO: { score: 9, rank: 178 }, // Somalia
  SS: { score: 8, rank: 179 }, // South Sudan
};

export function getCpi(iso2: string): CpiEntry | undefined {
  return CPI_RANK[iso2];
}

export function hasCpi(iso2: string): boolean {
  return iso2 in CPI_RANK;
}
