/**
 * Transparency International — Corruption Perceptions Index (CPI) snapshot.
 *
 * Score 0–100 (HIGHER = cleaner / less corrupt) + rank (1 = cleanest) within the
 * 2025 table (182 countries ranked; official published rank).
 *
 * DISPLAY-ONLY. CPI is licensed CC BY-ND: we show it unmodified and NEVER feed it
 * into the RegActions Country Risk Score (the scored corruption signal comes from
 * the World Bank WGI Control-of-Corruption dimension). Attribution required.
 *
 * GENERATED by scripts/ingest-cpi.ts. Do not edit by hand — re-run to refresh.
 */

export const CPI_YEAR = "2025";
export const CPI_TOTAL = 182;
export const CPI_SOURCE = "https://www.transparency.org/en/cpi/2025";
export const CPI_LICENCE = "CC BY-ND 4.0 — Transparency International";

export interface CpiEntry {
  /** 0–100, higher = cleaner. */
  score: number;
  /** 1 = cleanest; out of CPI_TOTAL. */
  rank: number;
}

/** iso2 -> CPI score + rank (2025). Display only, never scored. */
export const CPI_RANK: Record<string, CpiEntry> = {
  DK: { score: 89, rank: 1 }, // Denmark
  FI: { score: 88, rank: 2 }, // Finland
  SG: { score: 84, rank: 3 }, // Singapore
  NZ: { score: 81, rank: 4 }, // New Zealand
  NO: { score: 81, rank: 4 }, // Norway
  SE: { score: 80, rank: 6 }, // Sweden
  CH: { score: 80, rank: 6 }, // Switzerland
  LU: { score: 78, rank: 8 }, // Luxembourg
  NL: { score: 78, rank: 8 }, // Netherlands
  DE: { score: 77, rank: 10 }, // Germany
  IS: { score: 77, rank: 10 }, // Iceland
  AU: { score: 76, rank: 12 }, // Australia
  EE: { score: 76, rank: 12 }, // Estonia
  HK: { score: 76, rank: 12 }, // Hong Kong
  IE: { score: 76, rank: 12 }, // Ireland
  CA: { score: 75, rank: 16 }, // Canada
  UY: { score: 73, rank: 17 }, // Uruguay
  BT: { score: 71, rank: 18 }, // Bhutan
  JP: { score: 71, rank: 18 }, // Japan
  GB: { score: 70, rank: 20 }, // United Kingdom
  AT: { score: 69, rank: 21 }, // Austria
  BE: { score: 69, rank: 21 }, // Belgium
  AE: { score: 69, rank: 21 }, // United Arab Emirates
  BB: { score: 68, rank: 24 }, // Barbados
  SC: { score: 68, rank: 24 }, // Seychelles
  TW: { score: 68, rank: 24 }, // Taiwan
  FR: { score: 66, rank: 27 }, // France
  LT: { score: 65, rank: 28 }, // Lithuania
  BS: { score: 64, rank: 29 }, // Bahamas
  US: { score: 64, rank: 29 }, // United States
  BN: { score: 63, rank: 31 }, // Brunei
  CL: { score: 63, rank: 31 }, // Chile
  KR: { score: 63, rank: 31 }, // South Korea
  CV: { score: 62, rank: 35 }, // Cabo Verde
  IL: { score: 62, rank: 35 }, // Israel
  LV: { score: 60, rank: 37 }, // Latvia
  CZ: { score: 59, rank: 39 }, // Czechia
  BW: { score: 58, rank: 41 }, // Botswana
  QA: { score: 58, rank: 41 }, // Qatar
  RW: { score: 58, rank: 41 }, // Rwanda
  SI: { score: 58, rank: 41 }, // Slovenia
  SA: { score: 57, rank: 45 }, // Saudi Arabia
  CR: { score: 56, rank: 46 }, // Costa Rica
  PT: { score: 56, rank: 46 }, // Portugal
  CY: { score: 55, rank: 49 }, // Cyprus
  FJ: { score: 55, rank: 49 }, // Fiji
  ES: { score: 55, rank: 49 }, // Spain
  IT: { score: 53, rank: 52 }, // Italy
  PL: { score: 53, rank: 52 }, // Poland
  MY: { score: 52, rank: 54 }, // Malaysia
  OM: { score: 52, rank: 54 }, // Oman
  BH: { score: 50, rank: 56 }, // Bahrain
  GR: { score: 50, rank: 56 }, // Greece
  JO: { score: 50, rank: 56 }, // Jordan
  MT: { score: 49, rank: 60 }, // Malta
  MU: { score: 48, rank: 61 }, // Mauritius
  SK: { score: 48, rank: 61 }, // Slovakia
  HR: { score: 47, rank: 63 }, // Croatia
  VU: { score: 47, rank: 63 }, // Vanuatu
  KW: { score: 46, rank: 65 }, // Kuwait
  ME: { score: 46, rank: 65 }, // Montenegro
  NA: { score: 46, rank: 65 }, // Namibia
  SN: { score: 46, rank: 65 }, // Senegal
  BJ: { score: 45, rank: 70 }, // Benin
  RO: { score: 45, rank: 70 }, // Romania
  ST: { score: 45, rank: 70 }, // São Tomé and Príncipe
  JM: { score: 44, rank: 73 }, // Jamaica
  TL: { score: 44, rank: 73 }, // Timor-Leste
  CN: { score: 43, rank: 76 }, // China
  CI: { score: 43, rank: 76 }, // Côte d'Ivoire
  GH: { score: 43, rank: 76 }, // Ghana
  MD: { score: 42, rank: 80 }, // Moldova
  ZA: { score: 41, rank: 81 }, // South Africa
  TT: { score: 41, rank: 81 }, // Trinidad and Tobago
  VN: { score: 41, rank: 81 }, // Vietnam
  BG: { score: 40, rank: 84 }, // Bulgaria
  BF: { score: 40, rank: 84 }, // Burkina Faso
  CU: { score: 40, rank: 84 }, // Cuba
  GY: { score: 40, rank: 84 }, // Guyana
  HU: { score: 40, rank: 84 }, // Hungary
  MK: { score: 40, rank: 84 }, // North Macedonia
  TZ: { score: 40, rank: 84 }, // Tanzania
  AL: { score: 39, rank: 91 }, // Albania
  IN: { score: 39, rank: 91 }, // India
  MV: { score: 39, rank: 91 }, // Maldives
  MA: { score: 39, rank: 91 }, // Morocco
  TN: { score: 39, rank: 91 }, // Tunisia
  ET: { score: 38, rank: 96 }, // Ethiopia
  KZ: { score: 38, rank: 96 }, // Kazakhstan
  SR: { score: 38, rank: 96 }, // Suriname
  CO: { score: 37, rank: 99 }, // Colombia
  DO: { score: 37, rank: 99 }, // Dominican Republic
  LS: { score: 37, rank: 99 }, // Lesotho
  GM: { score: 37, rank: 99 }, // The Gambia
  ZM: { score: 37, rank: 99 }, // Zambia
  AR: { score: 36, rank: 104 }, // Argentina
  UA: { score: 36, rank: 104 }, // Ukraine
  BR: { score: 35, rank: 107 }, // Brazil
  LK: { score: 35, rank: 107 }, // Sri Lanka
  DZ: { score: 34, rank: 109 }, // Algeria
  BA: { score: 34, rank: 109 }, // Bosnia and Herzegovina
  ID: { score: 34, rank: 109 }, // Indonesia
  LA: { score: 34, rank: 109 }, // Laos
  MW: { score: 34, rank: 109 }, // Malawi
  NP: { score: 34, rank: 109 }, // Nepal
  SL: { score: 34, rank: 109 }, // Sierra Leone
  EC: { score: 33, rank: 116 }, // Ecuador
  PA: { score: 33, rank: 116 }, // Panama
  RS: { score: 33, rank: 116 }, // Serbia
  TH: { score: 33, rank: 116 }, // Thailand
  AO: { score: 32, rank: 120 }, // Angola
  SV: { score: 32, rank: 120 }, // El Salvador
  PH: { score: 32, rank: 120 }, // Philippines
  TG: { score: 32, rank: 120 }, // Togo
  BY: { score: 31, rank: 124 }, // Belarus
  DJ: { score: 31, rank: 124 }, // Djibouti
  MN: { score: 31, rank: 124 }, // Mongolia
  NE: { score: 31, rank: 124 }, // Niger
  TR: { score: 31, rank: 124 }, // Türkiye
  UZ: { score: 31, rank: 124 }, // Uzbekistan
  EG: { score: 30, rank: 130 }, // Egypt
  KE: { score: 30, rank: 130 }, // Kenya
  MR: { score: 30, rank: 130 }, // Mauritania
  PE: { score: 30, rank: 130 }, // Peru
  GA: { score: 29, rank: 135 }, // Gabon
  BO: { score: 28, rank: 136 }, // Bolivia
  IQ: { score: 28, rank: 136 }, // Iraq
  LR: { score: 28, rank: 136 }, // Liberia
  ML: { score: 28, rank: 136 }, // Mali
  PK: { score: 28, rank: 136 }, // Pakistan
  MX: { score: 27, rank: 141 }, // Mexico
  CM: { score: 26, rank: 142 }, // Cameroon
  GT: { score: 26, rank: 142 }, // Guatemala
  GN: { score: 26, rank: 142 }, // Guinea
  KG: { score: 26, rank: 142 }, // Kyrgyzstan
  NG: { score: 26, rank: 142 }, // Nigeria
  PG: { score: 26, rank: 142 }, // Papua New Guinea
  MG: { score: 25, rank: 148 }, // Madagascar
  UG: { score: 25, rank: 148 }, // Uganda
  BD: { score: 24, rank: 150 }, // Bangladesh
  CF: { score: 24, rank: 150 }, // Central African Republic
  PY: { score: 24, rank: 150 }, // Paraguay
  SZ: { score: 23, rank: 153 }, // Eswatini
  IR: { score: 23, rank: 153 }, // Iran
  LB: { score: 23, rank: 153 }, // Lebanon
  CG: { score: 23, rank: 153 }, // Republic of the Congo
  TD: { score: 22, rank: 157 }, // Chad
  HN: { score: 22, rank: 157 }, // Honduras
  RU: { score: 22, rank: 157 }, // Russia
  ZW: { score: 22, rank: 157 }, // Zimbabwe
  GW: { score: 21, rank: 161 }, // Guinea-Bissau
  MZ: { score: 21, rank: 161 }, // Mozambique
  KH: { score: 20, rank: 163 }, // Cambodia
  KM: { score: 20, rank: 163 }, // Comoros
  CD: { score: 20, rank: 163 }, // Democratic Republic of the Congo
  TJ: { score: 19, rank: 166 }, // Tajikistan
  BI: { score: 17, rank: 167 }, // Burundi
  TM: { score: 17, rank: 167 }, // Turkmenistan
  AF: { score: 16, rank: 169 }, // Afghanistan
  HT: { score: 16, rank: 169 }, // Haiti
  MM: { score: 16, rank: 169 }, // Myanmar
  GQ: { score: 15, rank: 172 }, // Equatorial Guinea
  KP: { score: 15, rank: 172 }, // North Korea
  SY: { score: 15, rank: 172 }, // Syria
  NI: { score: 14, rank: 175 }, // Nicaragua
  SD: { score: 14, rank: 175 }, // Sudan
  ER: { score: 13, rank: 177 }, // Eritrea
  LY: { score: 13, rank: 177 }, // Libya
  YE: { score: 13, rank: 177 }, // Yemen
  VE: { score: 10, rank: 180 }, // Venezuela
  SO: { score: 9, rank: 181 }, // Somalia
  SS: { score: 9, rank: 181 }, // South Sudan
};

export function getCpi(iso2: string): CpiEntry | undefined {
  return CPI_RANK[iso2];
}

export function hasCpi(iso2: string): boolean {
  return iso2 in CPI_RANK;
}
