/** GENERATED by scripts/country-risk/promote-sanctions-snapshot.ts.
 * Do not hand-edit. Promotion requires complete independent review and a
 * current, stable four-source assurance report.
 */
import type {
  CountrySanctions,
  SanctionsImposer,
  SanctionsProgram,
  SanctionsTier,
} from "./sanctionsStatus.js";
import type { SanctionsRegimeRelationship } from "./sanctionsRegimeCandidates.js";

export interface ApprovedSanctionsProgram extends SanctionsProgram {
  imposer: SanctionsImposer;
  tier: SanctionsTier;
  relationship: SanctionsRegimeRelationship;
  catalogueUrl: string;
  evidenceUrl: string;
  reviewedBy: string;
  reviewerOrganisation: string;
  reviewedAt: string;
  reviewNote: string;
}

export interface ApprovedCountrySanctions extends CountrySanctions {
  programs: ApprovedSanctionsProgram[];
}

export interface ApprovedSanctionsSource {
  id: string;
  url: string;
  retrievedAt: string;
  rawSha256: string;
  fingerprint: string;
}

export interface ApprovedSanctionsSnapshotMetadata {
  version: string | null;
  coverageComplete: boolean;
  effectiveAt: string | null;
  generatedAt: string | null;
  sha256: string | null;
  sourceReportSha256: string | null;
  candidateCount: number;
  approvedCount: number;
  rejectedCount: number;
  countryCount: number;
  sources: ApprovedSanctionsSource[];
}

export const SANCTIONS_APPROVED_SNAPSHOT: ApprovedSanctionsSnapshotMetadata = {
  "version": "sanctions-2026-07-17-70861f0f048e",
  "coverageComplete": true,
  "effectiveAt": "2026-07-17",
  "generatedAt": "2026-07-17T07:05:16.277Z",
  "sha256": "70861f0f048e6f7afacfbe8162e80c3cfd7fc988902dd3f4e77347e22bd02ca0",
  "sourceReportSha256": "04708529bcf99665e163db838d94afb0c89eb0bb802f6b01667f9eeb0d8dc5aa",
  "candidateCount": 94,
  "approvedCount": 90,
  "rejectedCount": 4,
  "countryCount": 31,
  "sources": [
    {
      "id": "eu-resources",
      "url": "https://finance.ec.europa.eu/eu-and-world/sanctions-restrictive-measures/overview-sanctions-and-related-resources_en",
      "retrievedAt": "2026-07-17T06:58:54.687Z",
      "rawSha256": "025eef518779724d7420e5090bd98ef4bd72be8082d56b923fd8eaf1ead1b971",
      "fingerprint": "c1b9e34e9054e25837027df1ba8cf67570d9525254f9552a8ba307001c5b684b"
    },
    {
      "id": "ofac-programmes",
      "url": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
      "retrievedAt": "2026-07-17T06:58:54.849Z",
      "rawSha256": "09e6e33ab2414fd105b2df4efc4e5b8200169710e048a2de892a640c975c6654",
      "fingerprint": "69620fbe766e2114eda53f2f4ace520f9b63576b31fb07c2eafcf6cd2072764c"
    },
    {
      "id": "uk-regimes",
      "url": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
      "retrievedAt": "2026-07-17T06:58:54.707Z",
      "rawSha256": "1676147c887fda34f0e382b095638486466808a3d607d2f99211215968dc6e4d",
      "fingerprint": "d03bedee11bc6f840ef215deeaad5a6888f7f3623fc98c773bcb0d88e56e3b1a"
    },
    {
      "id": "un-consolidated-list",
      "url": "https://scsanctions.un.org/resources/xml/en/name/consolidated.xml",
      "retrievedAt": "2026-07-17T06:58:56.423Z",
      "rawSha256": "b04666a9fbf8cb54482a5f6d0311757a29b05bcf3a9d6cb618e843918bceb22c",
      "fingerprint": "293d47ec8abcf223a380298c33afa4bd0dc55b68d323edae28a3f492ee6ca41a"
    }
  ]
};

export const SANCTIONS_APPROVED_STATUS: ApprovedCountrySanctions[] = [
  {
    "iso2": "AF",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Afghanistan restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=1&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=1&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Afghanistan (AF); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Afghanistan-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/afghanistan-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/afghanistan-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Afghanistan (AF); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Afghanistan sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/afghanistan-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/afghanistan-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Afghanistan (AF); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "1988 Taliban sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1988",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1988",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Afghanistan (AF); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "BA",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Bosnia and Herzegovina restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=4&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=4&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Bosnia and Herzegovina (BA); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Bosnia and Herzegovina sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/bosnia-and-herzegovina-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/bosnia-and-herzegovina-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Bosnia and Herzegovina (BA); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "BI",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Burundi restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=7&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=7&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Burundi (BI); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "BY",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Belarus restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=2&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=2&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Belarus (BY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "sectoral",
        "program": "Belarus Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/belarus-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/belarus-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: OFAC maintains an active country regime for Belarus (BY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Republic of Belarus sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/republic-of-belarus-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/republic-of-belarus-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Belarus (BY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "CD",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Democratic Republic of the Congo restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=11&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=11&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Democratic Republic of the Congo (CD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Democratic Republic of the Congo-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/democratic-republic-of-the-congo-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/democratic-republic-of-the-congo-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Democratic Republic of the Congo (CD); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Democratic Republic of the Congo sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/the-democratic-republic-of-the-congo-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/the-democratic-republic-of-the-congo-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Democratic Republic of the Congo (CD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "1533 Democratic Republic of the Congo sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1533",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1533",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Democratic Republic of the Congo (CD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "CF",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Central African Republic restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=9&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=9&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Central African Republic (CF); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Central African Republic Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/central-african-republic-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/central-african-republic-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Central African Republic (CF); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Central African Republic sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/central-african-republic-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/central-african-republic-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Central African Republic (CF); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "2745 Central African Republic sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2745",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2745",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Central African Republic (CF); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "CN",
    "programs": [
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Chinese Military Companies Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/chinese-military-companies-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/chinese-military-companies-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for China (CN); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "UK arms embargo on mainland China and Hong Kong",
        "sourceUrl": "https://www.gov.uk/guidance/uk-arms-embargo-on-mainland-china-and-hong-kong",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/guidance/uk-arms-embargo-on-mainland-china-and-hong-kong",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for China (CN); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "CU",
    "programs": [
      {
        "imposer": "OFAC",
        "tier": "comprehensive",
        "program": "Cuba Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/cuba-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/cuba-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at comprehensive: OFAC maintains an active country regime for Cuba (CU); confirmed a broad country-wide trade and financial embargo. Verified against the OFAC official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "ET",
    "programs": [
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Ethiopia-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/ethiopia",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/ethiopia",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Ethiopia (ET); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "GN",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Guinea restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=14&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=14&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Guinea (GN); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Guinea sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/guinea-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/guinea-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Guinea (GN); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "GW",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Guinea-Bissau restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=15&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=15&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Guinea-Bissau (GW); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Republic of Guinea-Bissau sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/guinea-bissau-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/guinea-bissau-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Guinea-Bissau (GW); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "2048 Guinea-Bissau sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2048",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2048",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Guinea-Bissau (GW); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "HK",
    "programs": [
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Hong Kong-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/hong-kong-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/hong-kong-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Hong Kong (HK); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "UK arms embargo on mainland China and Hong Kong",
        "sourceUrl": "https://www.gov.uk/guidance/uk-arms-embargo-on-mainland-china-and-hong-kong",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/guidance/uk-arms-embargo-on-mainland-china-and-hong-kong",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Hong Kong (HK); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "HT",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Haiti restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=54&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=54&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Haiti (HT); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Haiti sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/haiti-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/haiti-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Haiti (HT); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "2653 Haiti sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2653",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2653",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Haiti (HT); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "IQ",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Iraq restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=19&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=19&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Iraq (IQ); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Iraq-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/iraq-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/iraq-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Iraq (IQ); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Iraq sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/iraq-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/iraq-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Iraq (IQ); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "1518 Iraq sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1518",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1518",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Iraq (IQ); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "IR",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Iran restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=18&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=18&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Iran (IR); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "comprehensive",
        "program": "Iran Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/iran-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/iran-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at comprehensive: OFAC maintains an active country regime for Iran (IR); confirmed a broad country-wide trade and financial embargo. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Iran and Iran nuclear sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/iran-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/iran-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Iran (IR); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "1737 Iran sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1737",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1737",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Iran (IR); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "KP",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "North Korea restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=20&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=20&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for North Korea (KP); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "comprehensive",
        "program": "North Korea Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/north-korea-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/north-korea-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at comprehensive: OFAC maintains an active country regime for North Korea (KP); confirmed a broad country-wide trade and financial embargo. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Democratic People's Republic of Korea sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/democratic-peoples-republic-of-korea-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/democratic-peoples-republic-of-korea-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for North Korea (KP); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "1718 DPRK sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1718",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1718",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for North Korea (KP); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "LB",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Lebanon restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=51&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=51&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Lebanon (LB); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Lebanon-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/lebanon-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/lebanon-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Lebanon (LB); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Lebanon sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/lebanon-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/lebanon-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Lebanon (LB); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "1636 Lebanon sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1636",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1636",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Lebanon (LB); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "LY",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Libya restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=23&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=23&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Libya (LY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Libya Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/libya-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/libya-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Libya (LY); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Libya sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/libya-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/libya-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Libya (LY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "1970 Libya sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1970",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1970",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Libya (LY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "ML",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Mali restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=42&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=42&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Mali (ML); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Mali-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/mali-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/mali-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Mali (ML); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Mali sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/mali-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/mali-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Mali (ML); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "MM",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Myanmar restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=8&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=8&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Myanmar (MM); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Burma-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/burma",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/burma",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Myanmar (MM); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Myanmar sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/myanmar-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/myanmar-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Myanmar (MM); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "NE",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Niger restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=58&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=58&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Niger (NE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "NI",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Nicaragua restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=48&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=48&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Nicaragua (NI); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Nicaragua-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/nicaragua-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/nicaragua-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Nicaragua (NI); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Nicaragua sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/nicaragua-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/nicaragua-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Nicaragua (NI); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "RU",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Russia restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=61&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=61&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Russia (RU); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "sectoral",
        "program": "Russian Harmful Foreign Activities and Ukraine-/Russia-related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/russian-harmful-foreign-activities-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/russian-harmful-foreign-activities-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: OFAC maintains an active country regime for Russia (RU); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Russia sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/russia-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/russia-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Russia (RU); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "SD",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Sudan restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=31&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=31&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Sudan (SD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Sudan and Darfur Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/sudan-and-darfur-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/sudan-and-darfur-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Sudan (SD); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Sudan sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/sudan-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/sudan-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Sudan (SD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "1591 Sudan sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/1591",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/1591",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Sudan (SD); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "SO",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Somalia restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=29&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=29&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Somalia (SO); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Somalia Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/somalia-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/somalia-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Somalia (SO); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Somalia sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/somalia-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/somalia-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Somalia (SO); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "Al-Shabaab / Somalia sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2713",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2713",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for Somalia (SO); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "SS",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "South Sudan restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=30&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=30&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for South Sudan (SS); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "South Sudan-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/south-sudan-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/south-sudan-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for South Sudan (SS); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "South Sudan sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/south-sudan-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/south-sudan-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for South Sudan (SS); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "sectoral",
        "program": "2206 South Sudan sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2206",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2206",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UN maintains an active country regime for South Sudan (SS); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "SY",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Syria restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=32&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=32&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Syria (SY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Promoting Accountability for Assad and Regional Stabilization Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/paarss",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/paarss",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Syria (SY); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Syria sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/syria-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/syria-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Syria (SY); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "TN",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Tunisia restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=33&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=33&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Tunisia (TN); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "VE",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Venezuela restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=44&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=44&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Venezuela (VE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "sectoral",
        "program": "Venezuela-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/venezuela-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/venezuela-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: OFAC maintains an active country regime for Venezuela (VE); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Venezuela sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/venezuela-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/venezuela-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Venezuela (VE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "YE",
    "programs": [
      {
        "imposer": "EU",
        "tier": "targeted",
        "program": "Yemen restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=39&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=39&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: EU maintains an active country regime for Yemen (YE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "OFAC",
        "tier": "targeted",
        "program": "Yemen-Related Sanctions",
        "sourceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/yemen-related-sanctions",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
        "evidenceUrl": "https://ofac.treasury.gov/sanctions-programs-and-country-information/yemen-related-sanctions",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: OFAC maintains an active country regime for Yemen (YE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the OFAC official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "targeted",
        "program": "Yemen sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/yemen-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/yemen-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UK maintains an active country regime for Yemen (YE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UK official catalogue on 2026-07-17."
      },
      {
        "imposer": "UN",
        "tier": "targeted",
        "program": "2140 Yemen sanctions",
        "sourceUrl": "https://main.un.org/securitycouncil/en/sanctions/2140",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://main.un.org/securitycouncil/en/sanctions/information",
        "evidenceUrl": "https://main.un.org/securitycouncil/en/sanctions/2140",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at targeted: UN maintains an active country regime for Yemen (YE); confirmed restrictions attaching principally to designated persons/entities with no material country-wide class of ordinary transactions. Verified against the UN official catalogue on 2026-07-17."
      }
    ]
  },
  {
    "iso2": "ZW",
    "programs": [
      {
        "imposer": "EU",
        "tier": "sectoral",
        "program": "Zimbabwe restrictive measures",
        "sourceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=40&lang=en",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.consilium.europa.eu/en/topics/sanctions/",
        "evidenceUrl": "https://www.sanctionsmap.eu/api/v1/pdf/regime?id%5B%5D=40&lang=en",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: EU maintains an active country regime for Zimbabwe (ZW); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the EU official catalogue on 2026-07-17."
      },
      {
        "imposer": "UK",
        "tier": "sectoral",
        "program": "Zimbabwe sanctions",
        "sourceUrl": "https://www.gov.uk/government/publications/zimbabwe-sanctions-guidance",
        "reviewed": "2026-07",
        "relationship": "direct-country-exposure",
        "catalogueUrl": "https://www.gov.uk/government/collections/uk-sanctions-regimes-under-the-sanctions-act",
        "evidenceUrl": "https://www.gov.uk/government/publications/zimbabwe-sanctions-guidance",
        "reviewedBy": "A. Omosanya",
        "reviewerOrganisation": "RegActions country-risk compliance review",
        "reviewedAt": "2026-07-17T00:00:00.000Z",
        "reviewNote": "Approved at sectoral: UK maintains an active country regime for Zimbabwe (ZW); confirmed a non-designation restriction on a material class of transactions, goods or a sector (including a country-wide arms embargo). Verified against the UK official catalogue on 2026-07-17."
      }
    ]
  }
];

const BY_ISO2 = new Map(SANCTIONS_APPROVED_STATUS.map((record) => [record.iso2, record]));

export function getApprovedSanctions(iso2: string): ApprovedCountrySanctions | undefined {
  return BY_ISO2.get(iso2.toUpperCase());
}
